### ISSUE TITLE
chunk_target_size does not increase chunk file size as intended;

### ISSUE THREAD

**Issue by lyt5664681** [grafana/loki#10174]
I have a feeling that my Loki's chunks files are too small, averaging only a few hundred kilobytes, while my configuration is set to 50m. Can you please help me identify where the problem might be? Here's my complete configuration file. I'm using Loki version 2.2.1.

[loki-local-config.txt](https://github.com/grafana/loki/files/12274277/loki-local-config.txt)

![475023d67687e62705d5e1c69d0308b](https://github.com/grafana/loki/assets/15962612/c5e4e60b-9321-4791-af53-2ee6de8dd4fc)

**Comment by DylanGuedes** [comment]
Hey, thank you for your report.

Your chunks have less than the target size because they're being flushed (i.e: closed) for a different reason. I recommend you to check the `loki_ingester_chunks_flushed_total` metric.

I'm closing the issue as this isn't a bug, if you think you found a misbehavior please reopen this one.
