### ISSUE TITLE
Ingester crashes on exit

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#105]
Spotted on one of the ingesters:
```
level=info ts=2018-12-14T09:13:39.379995933Z caller=gokit.go:36 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2018-12-14T09:13:39.382026879Z caller=loki.go:158 msg=stopping module=store
level=info ts=2018-12-14T09:13:39.382126813Z caller=loki.go:158 msg=stopping module=ingester
level=info ts=2018-12-14T09:13:39.382174645Z caller=lifecycler.go:443 msg="changing ingester state from" old_state=ACTIVE new_state=LEAVING
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xbbfa8c]

goroutine 88517526 [running]:
github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open.func1(0xc077ed3860, 0xc15b1dc780, 0xc06cc148c0, 0xc231538280, 0x1, 0x1)
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:118 +0xfc
created by github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:108 +0x471
```

**Comment by tomwilkie** [comment]
I suspect this is due to an uninitialised store somewhere, but I got side tracked digging into it.

**Comment by woodsaj** [comment]
currently the shutdown logic is stopping dependencies before stopping modules :(

https://github.com/grafana/loki/blob/master/pkg/loki/loki.go#L147-L165

The shutdown logic is going to need to be a lot more intelligent. When shutting down we need to build the full dependency tree and and then order the shutdowns so that we dont ever shut down a module that is dependent on another module that is still running.

**Comment by tomwilkie** [comment]
Good catch!  Should be an easy fix though; we have the dependancy tree, we should shutdown parents before children.  I think moving this line up will suffice: https://github.com/grafana/loki/blob/master/pkg/loki/loki.go#L162
