### ISSUE TITLE
Easier way to select the logForwarder in the loki-stack helm chart

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1075]
As of today you can choose which log forwarder you want to use within the [loki-stack chart](https://github.com/grafana/loki/tree/master/production/helm/loki-stack) by doing:

For promtail:

```
helm upgrade --install loki loki/loki-stack
```

For fluent-bit:

```bash
helm upgrade --install loki loki/loki-stack \
    --set fluent-bit.enabled=true,promtail.enabled=false
```

It would be great if we could instead use property in the loki-stack chart values as such:

```json
logForwarder: [ promtail | fluent-bit | none ]
```

This way we could install the log forwarder of our choice using:

```
helm upgrade --install loki loki/loki-stack \
    --set logForwarder=fluent-bit
```

/cc @joe-elliott

**Comment by sharmaanshul21** [comment]
@cyriltovena I can look into this :bowtie:

**Comment by cyriltovena** [comment]
Sure go ahead !

**Comment by kessiler** [comment]
@sharmaanshul21 r u going to work on this or can I take it? Happy to help here. 
cc @cyriltovena

**Comment by sharmaanshul21** [comment]
Sure, please go ahead, I am stuck till 15th, can’t pick this issue before that :-(

**Comment by kessiler** [comment]
Hi @cyriltovena, after some research here what you're trying to achieve is not possible today.

Helm doesn't support computed values in `requirements.yaml` (condition property).

Here's the draft: https://github.com/grafana/loki/pull/1140/files

I've tried to use _helpers.tpl to add dynamically the condition in values.yaml, however, it did not work.

There is an issue open for it in helm chart repo: https://github.com/helm/helm/issues/6525

Furthermore, the issue is located here: https://github.com/helm/helm/blob/2e871267def61b89feece273beb47ad6bb50b9b4/pkg/chartutil/requirements.go#L127-L179
This line https://github.com/helm/helm/blob/2e871267def61b89feece273beb47ad6bb50b9b4/pkg/chartutil/requirements.go#L146 it doesn't evaluate/compute the property.

**Comment by cyriltovena** [comment]
I'll check your PR.

**Comment by cyriltovena** [comment]
Yep you are right, Thanks @kessiler for the investigation, too bad helm doesn't support this.
