### ISSUE TITLE
docs: Labels recommendations

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1117]
I was searching through our recommendations for labels and couldn't find anything.

I think we should have in our user documentation some explanation about what are bad and good labels with some nice example.

Somwhere here https://github.com/grafana/loki/blob/master/docs/clients/README.md

We should also explain how to have the same labels in Prometheus and Why ? (switching from metrics to logs).

**Comment by rodrigoroma** [comment]
I have the following doubt about labels recommendations in Loki and maybe it differs from Prometheus in this point despite Loki being "Prometheus for logs":

In Prometheus, it's not recommended to create labels with a high number of different values (the user id or email for example) because it would create a lot of different time series. Does this apply to Loki? Or it's ok to create labels with a high cardinality in Loki?

**Comment by cyriltovena** [comment]
The same apply to Loki, you usually want to avoid latency as label as it is unbounded, but pod name is good label to have.

**Comment by rodrigoroma** [comment]
@cyriltovena I confess it's a little disappointing to me to not be able to filter by `userId` or `requestId` for example. 

Am I thinking the wrong way?!

**Comment by cyriltovena** [comment]
No at all, we use Loki to find jaeger traceid using logql filter.

You can still find those logs without having to label/index them

**Comment by takanabe** [comment]
Can I take over this issue to make me deeply understand the use cases 🤔?

**Comment by cyriltovena** [comment]
For sure

**Comment by slim-bean** [comment]
We did merge some [docs](https://github.com/grafana/loki/blob/master/docs/getting-started/labels.md) with some better guidance here.  Also see the [best practices](https://github.com/grafana/loki/blob/master/docs/best-practices/current-best-practices.md) some more info.
