### ISSUE TITLE
Ingest RabbitMQ (AMQP) messages into Loki

### ISSUE THREAD

**Issue by rodrigoroma** [grafana/loki#1146]
I think sending application log messages to RabbitMQ (or other queue system that implements AMQP protocol) is a good architetural decision because:
* It helps decouple the application
* It puts the log messages in a buffer in case of log system unavailability
* Increase the application speed as putting the logs in a queue sould be faster than sending then to the log system

I use this architeture when dealing with Graylog, but I couldn't find a way to put AMQP messages into Loki.

Promtail could connect to AMQP to retrieve the messages. Honestly, I don't know if it would be better than having a separate agent to do this.

**Comment by tivvit** [comment]
I am working on implementing Kafka queue as input to Loki for the exact same reasons you stated. I will publish `kafka2loki` project which is client reading messages from Kafka and sending them to Loki using Promtal client.

**Comment by tesharp** [comment]
Maybe this can be opened again? I started on a simple kafka implementation https://github.com/tesharp/loki. To configure it you can define a kafka target:

```golang
scrape_configs:
- job_name: kafka
  kafka:
    brokers:
      - kafka-host:9093
    groupId: test
    topic: testtopic
    plain:
      username: username
      password: password

    labels:
      job: kafka
  
  pipeline_stages:
    - json:
        expressions:
      ...
```

I used kafka instead of AMQP simply because it was easier to deal with consumer groups and rebalancing. In our case the events in kafka contains multiple logs though, so currently it will split each incoming message and call the handler multiple times for each entry.

Just testing this for our purpose now. Will work a bit more on it and maybe it can be useful for others too
