### ISSUE TITLE
Implement promtail loki_push_api gRPC server

### ISSUE THREAD

**Issue by chamini2** [grafana/loki#11547]
**Is your feature request related to a problem? Please describe.**
I am using Promtail to push logs to Loki and it returns

```
{grpc_message:"unknown service logproto.Pusher", grpc_status:12, created_time:"2023-12-21T18:14:55.953064362+00:00"}
```

So it seems the `loki_push_api` config does not implement gRPC.

**Describe the solution you'd like**
Implement the `logproto.Pusher` server to enable gRPC.

**Describe alternatives you've considered**
Sending HTTP requests, but I have a very large amount of logs I'm sending this way, so it seems gRPC would be ideal.
Also, I receive the logs in my service in proto format too, so it makes sense to minimize data transformations.

**Additional context**

*****

It seems where the `loki_push_api` is setup and started is 

https://github.com/grafana/loki/blob/d8c881a219ed03150ef354be71e7bcbc54aa94c3/clients/pkg/promtail/targets/lokipush/pushtarget.go#L72-L82

**Comment by JStickler** [comment]
We're currently reevaluating Promtail's position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point. Additionally, the agent team is more likely to have time to dedicate to your issue
While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.

**Comment by chamini2** [comment]
Thanks for the response, is there an equivalent in Agent to `loki_push_api`, @JStickler?

**Comment by cstyan** [comment]
@chamini2 the agent essentially contains a hard for of promtail, so it can be used to write logs to Loki and has now had more additions made to it. Whether it supports GRPC for that or not already I'm not sure.

**Comment by chamini2** [comment]
Well, I moved to Agent. It does not implement gRPC either. Thanks for the information either way!

**Comment by chamini2** [comment]
created https://github.com/grafana/agent/issues/6025
