### ISSUE TITLE
Actually plug http_listen_port and grpc_listen_port into helm code

### ISSUE THREAD

**Issue by bebosudo** [grafana/loki#11641]
**Describe the bug**
PR https://github.com/grafana/loki/pull/7137 (later amended by https://github.com/grafana/loki/pull/7174) introduced some server configs, but it seems that they weren't fully plugged the helm code, causing some problems when they get set to something different from the default.

**To Reproduce**
1. install loki with helm and set the `loki.server.grpc_listen_port` value to e.g. `9096`
2. the `loki-read` pod logs will start showing lots and lots of errors like the following:

```
level=warn ts=2024-01-10T16:32:00.721694775Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.235:9095: connect: connection refused\"" addr=172.28.12.235:9095
level=warn ts=2024-01-10T16:32:00.735794161Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.13.194:9095: connect: connection refused\"" addr=172.28.13.194:9095
level=warn ts=2024-01-10T16:32:00.982868119Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.28.12.235:9095: connect: connection refused\"" addr=172.28.12.235:9095
```

This is because the `query-scheduler-discovery` headless service returns that port:

```
$ k get svc/query-scheduler-discovery -o yaml
...
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
```

**Expected behavior**

The backend service will use the configs because the port is passed as one of the parameters [here](https://github.com/grafana/loki/blob/0dc8c7533186c22b4649779f4098ea88aa82ff50/production/helm/loki/values.yaml#L97-L100).

The `query-scheduler-discovery` kubernetes service should also point to the requested port, but the helm template [doesn't use that variable, and instead uses the hardcoded value of `9095`](https://github.com/grafana/loki/blob/0dc8c7533186c22b4649779f4098ea88aa82ff50/production/helm/loki/templates/backend/service-backend-headless.yaml#L35).

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

---

I'll test a potential fix in the next days.

**Comment by Sheikh-Abubaker** [comment]
@bebosudo I would like to work on this issue,  but I can't find `loki.server.grpc_listen_port` parameter in values.yaml.

**Comment by castaway2000** [comment]
As of 5.46.0 app version 2.9.5 It still seems to be unresolved. I recently have been deploying to kubernetes with GKE and anthos and the target port is not showing up as a number. It's showing up as a string "grpc" or "http-metrics". 

It is directly related as a problem because there's only two variables that I can change in values.yaml and I'm not able to make any difference on target port however port can show up as normal. Unfortunately I can't provide information from my workstation which is using this but I can from my personal account. Apologies for the screenshot and not any console logs. However the symptoms are identical to what is being presented by OP. 
![IMG20240321155415](https://github.com/grafana/loki/assets/4655782/a51c8da7-f8b6-4023-bbc3-ed9cc6c04a57)

**Comment by MichelHollands** [comment]
@castaway2000 These "http-metrics" and "grpc" ports are named ports that are also updated to the same value. For example in the [statefulset](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L94) and the corresponding [service](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/service-write.yaml#L27). I don't quite get what problem you are having. Do you want to change each of these individually?

**Comment by castaway2000** [comment]
> @castaway2000 These "http-metrics" and "grpc" ports are named ports that are also updated to the same value. For example in the [statefulset](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/statefulset-write.yaml#L94) and the corresponding [service](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/write/service-write.yaml#L27). I don't quite get what problem you are having. Do you want to change each of these individually?

The problem is expected behavior should have the target port be a number not a string. in the default deployments for services in grafana, prometheus and others the "target port" deploys with a number that matches the "port". 

this makes it impossible to add the k8s loki service as grafana data source.
