### ISSUE TITLE
Logstash plugin

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1192]
I think it would be interesting to have a logstash plugin for folks that are using it and have it already configured.

info here: https://www.elastic.co/guide/en/logstash/current/contributing-java-plugin.html

/cc @slim-bean the java expert :)

**Comment by randomchance** [comment]
is there *any* way to get data from logstash to loki at present, even without a plugin?  My environment uses ELK, but we want to move away from it, both because it's so heavy and because we want to avoid installing java everywhere. 

I would love to replace the EK part with Loki - I still need the ability to transform and forward logs that logstash gives, and I haven't found a replacement I'm happy with for a windows stack.

**Comment by cyriltovena** [comment]
Not really but the Loki push API is fairly easy so writing a small exporter for your use case shouldn't be too much trouble.

**Comment by randomchance** [comment]
Alright, I'll give it a shot, thanks :)

**Comment by cyriltovena** [comment]
I’m working on a pipe to promtail feature that should help you.

**Comment by cyriltovena** [comment]
@randomchance you can pipe to promtail now, not sure if it helps a lot but that can be used to transfer data and/or test before transfering.

**Comment by vbichov** [comment]
@cyriltovena  any chance you could share link to the relevant docs?

**Comment by cyriltovena** [comment]
https://github.com/grafana/loki/blob/master/docs/clients/promtail/troubleshooting.md#pipe-data-to-promtail

**Comment by adityacs** [comment]
@randomchance I see that you are working on logstash plugin. If you already have your code ready, you can push and create your PR. I am OK to close my PR #1822 

Thanks

**Comment by randomchance** [comment]
@adityacs With everything going on I have not had a chance to even start on that, and it's been shelved for the future. The logstash plugin repo I do have is for VSCode, so don't wait on me!

**Comment by adityacs** [comment]
Thanks @randomchance
