### ISSUE TITLE
ImagePullSecret for loki memcached with error

### ISSUE THREAD

**Issue by V1ct0rHM** [grafana/loki#12632]
**Describe the bug**
The bug in this situation arises from a mismatch between the structure of the values provided in the values.yaml file and the way the template is trying to access them. 

In the template, the `.pullSecrets` field is being accessed under `$.ctx.Values.image.pullSecrets`. However, in the values.yaml file, the `imagePullSecrets` field is defined directly under the top-level key.

Because of this mismatch, when the template tries to access `.pullSecrets`, it encounters a nil pointer error because it expects the field to be nested under `image` and `pullSecrets`, but it's not structured that way in the values.yaml file.

To fix this bug, the template needs to be adjusted to directly access the `imagePullSecrets` field from the values.yaml file without assuming any nesting. This ensures that the template matches the structure of the provided values, preventing the nil pointer error.

**To Reproduce**
1. Started Loki helm chart 6.2.0
2. Started Promtail 6.15.5
3. No queries

**Expected behavior**
The expected behavior is that the Helm chart template correctly retrieves the `imagePullSecrets` field from the values.yaml file and uses it to populate the `imagePullSecrets` field in the generated Kubernetes manifests.

Specifically, when the template is rendered, it should iterate over the list of image pull secrets provided in the values.yaml file and include them in the generated StatefulSet manifest under the `spec.template.spec.imagePullSecrets` field.

The corrected behavior ensures that the Helm chart can be customized with the appropriate image pull secrets, allowing the deployment to access private Docker registries or other protected image sources as needed.

**Environment:**
 - Infrastructure: EKS 1.28
 - Deployment tool: Helm and ArgoCD

**Screenshots, Promtail config, or terminal output**
![image](https://github.com/grafana/loki/assets/102542832/d6f4b89d-bd40-47a5-bd1c-b9adf464c994)
![image](https://github.com/grafana/loki/assets/102542832/49d2f735-8fd7-4f90-a825-bb0cb6edb7fc)

I have a proposed change here: https://github.com/grafana/loki/blob/397aa56e157cbf733da548474a4bcae773e82362/production/helm/loki/templates/memcached/_memcached-statefulset.tpl#L75

To =>  {{- range $.ctx.Values.imagePullSecrets }}

**Comment by zesty-henitzhaki** [comment]
image:
    pullSecrets:
    - regcred

  imagePullSecrets:
  - name: regcred
  
  Quick Solution..
 Until the repair

**Comment by V1ct0rHM** [comment]
> ```
> image:
>   pullSecrets:
>   - regcred
> 
> imagePullSecrets:
> - name: regcred
> ```
>   
>   Quick Solution..
>  Until the repair
>   

I did this for now, thanks lmk if you want me to open a PR

**Comment by EvertonSA** [comment]
this is a very old discussion, I prefer imagePullSecrets but many grafana charts are using image.PullSecrets. 

not a simple change as many people would be affected

**Comment by fmannaixn** [comment]
What is holding up [Haibread's PR](https://github.com/grafana/loki/pull/13051) from being reviewed and merged? Should I update it and bump it to 6.6.7? Is there any other reason it didn't get reviewed by the Loki team?

This isn't a semantic discussion about whether the chart should use imagePullSecrets or image.pullSecrets, it's a bug where the template checks if **Values.imagePullSecrets** is defined, which is the value the other templates in the chart use, but then iterates over the nil value of **Values.image.pullSecrets**. I agree there is some inconsistency that could be cleaned up among the LGTM products, but this issue is purely a bug [in this one template](https://github.com/search?q=repo%3Agrafana%2Floki%20%2F%5CbpullSecrets%5Cb%2F&type=code).
