### ISSUE TITLE
logcli warning - "CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 1. Parsing will be abandoned"

### ISSUE THREAD

**Issue by kevinburke** [grafana/loki#12848]
When anyone at my company runs `logcli`, we get the following warning:

```
logcli[40075:863750] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
```

logcli was installed from Homebrew:

```
$ brew info logcli
==> logcli: stable 3.0.0 (bottled), HEAD
Run LogQL queries against a Loki server
https://grafana.com/loki
Installed
/opt/homebrew/Cellar/logcli/3.0.0 (6 files, 61.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-04-09 at 14:41:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/l/logcli.rb
License: AGPL-3.0-only
==> Dependencies
Build: go ✘
==> Options
--HEAD
	Install HEAD version
```

I haven't done more troubleshooting than this, but if you can give me advice on where to look I'd be happy to try to investigate further.

**Comment by kevinburkesegment** [comment]
Somehow something in the operating system is interpreting the query part of `logcli` as a plist argument. I can't reproduce it if I do `curl` or just do a plain Go HTTP request with the exact same text. 

```bash
# This triggers the warning
logcli query --limit=10 '{namespace="foo"}'

# These do not 
logcli query --limit=10 '{namespace="foo";}'
logcli query --limit=10 'namespace="foo";'
```

I am on a work machine so it may be some sort of bad interaction with crowdstrike, but if so that also seems concerning.

Looks like a similar issue here. https://github.com/foundry-rs/foundry/issues/7297

**Comment by erikdw** [comment]
Notably, we worked around this issue in `logcli` by rebuilding it using `CGO_ENABLED=0`.
