### ISSUE TITLE
Why is ingester.unregister-on-shutdown=false for Zone aware ingesters hardcoded?

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/loki#13071]
https://github.com/grafana/loki/blob/797bb641736a2355b4f8503c147fc0c8a814f19a/production/helm/loki/templates/ingester/statefulset-ingester-zone-b.yaml#L104

It's respectfully, very annoying to both have argument flags and configuration settings that do the same. This sends people on a chase in their config. Only to later realise that it's set as bin argument. 

I guess this consist of both a question and suggestion:

1. Why is this set as default? Is it required for zone aware ingesters? If so, why? 
2. Please, do not add this as arg, but make the config leading. IF it's required for zone aware ingesters, make an if/else in the values.yaml or some logic that 'forces' it to be `false`. 

For point 2, the whole thing is that helm templates are abstracted from us (users). Config values are leading. Having said value to default `true` and no mention of it being set to `false` is confusing.

Thanks in advance.

**Comment by vlad-diachenko** [comment]
Hey @wiardvanrij. 

> Why is this set as default? Is it required for zone aware ingesters? If so, why?

By default, it's set to false because it's expected that ingesters will be updated by zones. For example, at the beginning Zone A gets fully updated, after that B, and only after that C. 
Also, zonal statefulsets have an update strategy to force manual pod's update: 
```yaml
  updateStrategy:
    type: OnDelete
```
So, when all the ingesters of a single zone are down, we do not want them to unregister themselves from the ring to not re-shuffle the streams in working ingesters. If they leave the ring during the shutdown, token ranges will be changed and distributors will start sending streams to different ingesters, that will significantly increase the load on the cluster. 


> Please, do not add this as arg, but make the config leading. IF it's required for zone aware ingesters, make an if/else in the values.yaml or some logic that 'forces' it to be false.
You can use `.Values.ingester.extraArgs` and add override `-ingester.unregister-on-shutdown=true`. when Loki reads CLI flags, the last one takes precedence

**Comment by wiardvanrij** [comment]
I see, this makes a lot more sense. I will start to implement the operator, as I now get the whole idea that you all envisioned. Thanks!

**Comment by marshallford** [comment]
@vlad-diachenko How do you recommend configuring `ingester.unregister-on-shutdown` when setting up autoscaled zone aware ingesters? Before coming across this issue I had assumed that `ingester.unregister-on-shutdown` must be set to `true` when configuring auto scaling via an HPA -- in particular to allow for statefulset scale down cases. Thoughts?

Thank you!

**Comment by vlad-diachenko** [comment]
> [@vlad-diachenko](https://github.com/vlad-diachenko) How do you recommend configuring `ingester.unregister-on-shutdown` when setting up autoscaled zone aware ingesters? Before coming across this issue I had assumed that `ingester.unregister-on-shutdown` must be set to `true` when configuring auto scaling via an HPA -- in particular to allow for statefulset scale down cases. Thoughts?
> 
> Thank you!

Hey @marshallford.  If we are talking about scaling down, I still recommend using `ingester.unregister-on-shutdown=false` because before the shutdown, due to HPA scaling down, we need to call [prepare shutdown endpoint](https://grafana.com/docs/loki/latest/reference/loki-http-api/#prepare-ingester-shutdown) which will unregister the instance on shutdown... it's a kinda workaround to have `ingester.unregister-on-shutdown=true` behavior during scaling down, but not during restarts, reschedulings, or rollouts... 
does it make sense?
