### ISSUE TITLE
Promtail: High CPU usage with many completed Pods

### ISSUE THREAD

**Issue by Fabian-K** [grafana/loki#1315]
**Describe the bug**
We are running Loki in a cluster primarily used for job execution. As a result, we have many pods in the Completed phase. It looks like that the CPU usage of promtail is increasing with the number of Completed pods. After deleting the completed pods (in total 277), the CPU usage returns to normal values. 
In contrast to #1102 we only have a single node, therefore I´m opening a new issue.

**Environment:**
 - single node k8s cluster v1.14.8
 - Deployment tool: helm chart loki-stack, version 0.20.0, no customization

**Screenshots, Promtail config, or terminal output**
CPU usage of Promtail before and after deleting completed pods.
![image](https://user-images.githubusercontent.com/862577/69538459-a8c6fe00-0f82-11ea-9f92-2b198e2ad89f.png)

Thanks, Fabian

**Comment by slim-bean** [comment]
This still seems to be caused by the same underlying issue as #1102? I don't know that the number of nodes would make a difference, it's going to be based on the size of the results from the service discovery query.

**Comment by Fabian-K** [comment]
Thanks for your comment :) In my understanding, #1102 is about limiting the queries of promtail by using a node selector. This would still leave issues with a high number of pods (both running and completed) on individual nodes, right? Anyway, feel free to close the issue in case I´m getting this wrong!

**Comment by slim-bean** [comment]
Yeah this is true I see your point, if a single node has lots of pods I think this issue would still exist.  Though it's starting to feel to me like solving this is more about cleaning up the long list of completed pods rather than tuning the scrape config. 

Even if it was possible to only scrape pods which are not `completed` (which I'm not sure it is), this would still create a problem where the pod could transition to the `completed` state faster than the API is polled and therefore the logs would never get scraped (promtail would need to see the pod in a running state at least once to scrape the pods)

I think the only practical fix for this is to have something auto pruning completed pods?

**Comment by dragonsmith** [comment]
We are experiencing a similar problem: High Load Average with many completed Pods.

We have LA around ~250 on 40 core server with ~450 Completed pods.

Promtail fails its Liveness check in this situation once in a few hours.

I assume it is due to high number of inotify watchers.

```shell
# lsof -p 14201 | grep -c inotify
417
```
<img width="711" alt="Screenshot 2021-01-11 at 13 21 28" src="https://user-images.githubusercontent.com/511416/104168999-f06f4a00-540f-11eb-994b-e454822d8de5.png">

If I delete those Completed pods LA drops down to ~10.

**Comment by cyriltovena** [comment]
Could you grab me a pprof profile and share it here ?

```
curl localhost:3100/debug/pprof/profile\?seconds\=20
```

If not I'll try to reproduce this.

**Comment by dragonsmith** [comment]
@cyriltovena It will take us some time to reproduce, but I will come back with pprof results soon. Thank you!

**Comment by dragonsmith** [comment]
@cyriltovena Here it is:
[promtail.pprof.gz](https://github.com/grafana/loki/files/5984399/promtail.pprof.gz)

**Comment by cyriltovena** [comment]
Alright it's a mix between glob/fs syscall and watch/pool the filesystem.

First thing you could do is reduce the `sync_period` https://grafana.com/docs/loki/latest/clients/promtail/configuration/#target_config

![image](https://user-images.githubusercontent.com/1053421/108196624-4efea680-70e7-11eb-8ecb-d0d07b8f65b3.png)

Obviously the real solution is that we need a way to remove those completed pod. 🤔

**Comment by dethi** [comment]
We have the same issue. In our case, the completed jobs were created by our spinnaker pipelines, a little bit more than a thousand jobs. Removing the completed jobs helped, but still 600+ targets on the same promtail pod.

![image](https://user-images.githubusercontent.com/1011520/111808971-68ecfe00-88cc-11eb-8108-e92fbdbf48b2.png)

Which seems weird, I only see ~300 completed jobs left on the cluster. Need to investigate more.

Attaching a pprof profile and heap of the promtail pod. Flamegraph show the same things as above. Most of heap usage come from all the read buffers.
[pprof-promtail.zip](https://github.com/grafana/loki/files/6172643/Archive.zip)

**Comment by anarcher** [comment]
> Obviously the real solution is that we need a way to remove those completed pod.

I have same issue with argo-workflow's completed pods.. Can I remove those completed pod in scrape_configs?

**Comment by zhangzhiqiangcs** [comment]
+1 for this problem
