### ISSUE TITLE
debug image doesn't have debug symbols.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1338]
The makefile target `make loki-debug` uses -w which removes symbols.

This is due to LD_FLAGS.

**Comment by whothey** [comment]
Hi there,

Could I give it a try as my very first contribution?

I've managed it by removing the `-w` and `-s` flags, since `-s` strips the symbol table according to https://golang.org/pkg/cmd/link/internal/ld/#pkg-variables in the "Flags used by the linker" session.

Checked it through `go tool nm ./cmd/loki/loki-debug`, a giant list of symbols popped out.

I've also pushed the `-w -s` to the GO_FLAGS to prevent debug info in release binaries.

I'm just wondering if would be better to have an BASE_GO_LDFLAGS, to derive then DEBUG_GO_LDFLAGS and GO_LDFLAGS, but looks odd and overengineered.

**Comment by cyriltovena** [comment]
For sure I’ll take a look
