### ISSUE TITLE
Fix CVE-2024-6119 - OpenSSL (= update Alpine base-image to 3.20.3)

### ISSUE THREAD

**Issue by rgoltz** [grafana/loki#14140]
**Is your feature request related to a problem? Please describe.**
The current grafana loki docker image using Alpine 3.20.2. A CVE CVE-2024-6119 in OS-package `openssl` is resolved in Alpine 3.20.3: https://alpinelinux.org/posts/Alpine-3.17.10-3.18.9-3.19.4-3.20.3-released.html

**Describe the solution you'd like**
* [ ]  Update `alpine` Image tag `3.20.3` **OR**
* [ ]  Upgrade `openssl` to `3.3.2-r0` or Above (e.g. via apk update && apk upgrade openssl)

**Details from Image-Scan**
|   |   |   
| ------------- | ------------- | 
| Vulnerability ID | https://nvd.nist.gov/vuln/detail/CVE-2024-6119 |
| GitHub Advisory | https://github.com/advisories/GHSA-7m4m-pwhv-49c5 |
| CWE | https://cwe.mitre.org/data/definitions/843.html | 
| Severity     | High |
| Fix available      | Yes     |
| Installed version      | v3.3.1-r3     |
| Fix available      |  v3.3.2-r0   |
| Package Manager | OS |

**Comment by rgoltz** [comment]
@paul1r - Hi Paul, any chance that we can move to Alpine 3.20.3 to fix the CVE? - I've attached a PR (to the best of one's knowledge).

**Comment by paul1r** [comment]
@rgoltz Hello!  Very much appreciate the contribution! 

On Friday, I put together [this PR](https://github.com/grafana/loki/pull/14294) to finish up the move to Go 1.23, and tucked in the Alpine update as well, since the build image was being updated.  I just didn't get around to going through the open issues and PRs to see if someone had submitted this already to link them together and the like.

I hope this helps, and sorry for the delay!
