### ISSUE TITLE
Installation fails in Openshift

### ISSUE THREAD

**Issue by MastanaGuru** [grafana/loki#1458]
**Describe the bug**
Installing in openshift 3.11 using fails. The statefulset fails deploy with below error

**To Reproduce**
helm upgrade  --install loki -n openshift-loki loki/loki-stack     --set fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=false,prometheus.enabled=false,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false

**Environment:**
 - Infrastructure: Openshift 3.11
 - Deployment tool: helm

**Error**
create Pod loki-0 in StatefulSet loki failed error: pods "loki-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{10001}: 10001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 10001: must be in the ranges: [1000160000, 1000169999]]

**Comment by owen-d** [comment]
iirc, this is because openshift enforces certain fsgroup rules. It looks like the default supported range for your environment is `[1000160000, 1000169999]`.

You should be able to change the [security context](https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml#L140-L144) parameters for loki to fix this. I think that's `--set loki.securityContext.fsGroup=<new_value>`. Let us know if this works and feel free to close the issue once it's resolved.

**Comment by MastanaGuru** [comment]
I started the install with below values,  but still getting error "fsGroup: Invalid value: []int64{1000160100}: 1000160100 is not an allowed group]".
loki.securityContext.fsGroup=1000160100,
loki.securityContext.runAsGroup=1000160100,
loki.securityContext.runAsUser=1000160100

Project settings are 
openshift.io/sa.scc.supplemental-groups: 1000160000/10000
openshift.io/sa.scc.uid-range: 1000160000/10000

I see in the PodSecurityPolicy, fsGroup has a min:1 and max:65535. Would this causing the issue ?

**Comment by MastanaGuru** [comment]
Any advice ?

**Comment by owen-d** [comment]
Hey,

I don't have any experience running in Openshift so I'm not much help here. Perhaps Openshift is preventing this due to [security context constraints](https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#listing-security-context-constraints). 

I'm guessing you'll need to fix this problem through some combination of adjusting the `securityContext` in the loki helm chart and the above constraints in openshift.

If you resolve this, we'd really appreciate a documentation pr to help others getting started with loki+openshift.
