### ISSUE TITLE
Bloom filters based on structured metadata search chunks even if key does not exists

### ISSUE THREAD

**Issue by tiithansen** [grafana/loki#14614]
**Describe the bug**

Based on [this](https://github.com/grafana/loki/blob/7965722bb5a4f31cc68d30be0290e529c9aafe96/pkg/storage/bloom/v1/bloom_tester.go#L164-L172) even if metadata key is not present chunk is still considered to be used.

**Expected behavior**
If key nor value exist in metadata chunk should not be considered.

**Comment by chaudum** [comment]
Hi @tiithansen 

This is expected behaviour. The reason is that the requested label of the label filter expression _could_ be a regular label as well. We simply don't know it at this point, since the bloom gateway is only dealing with fingerprints (hashed labels of streams).

Yes, ideally we could dismiss all chunks. This is something we have on our radar and want to improve, because it can increase the filter rate by a lot.

**Comment by tiithansen** [comment]
Hmm, ok lets say I run query like
`{cluster="prod"} | trace_id="xxxx"` then it matches all chunks which have `trace_id` in it?

**Comment by chaudum** [comment]
> By _regular_ label you mean stream filter label?

Right.

We solved the problem with https://github.com/grafana/loki/pull/14661

**Comment by tiithansen** [comment]
Thanks, I will give it test.
