### ISSUE TITLE
Out of order errors with unique label set even after upgrading to v1.2

### ISSUE THREAD

**Issue by anish-lal** [grafana/loki#1464]
**Describe the bug**
Started getting `out of order` errors from ingester back when we installed loki v0.4 two months back. The issue is similar to the one described here https://github.com/grafana/loki/issues/898
Updated all the loki components to version 1.2 which should've fixed the out of order issues but didn't. There are occasional log drops when sending logs from promtail to loki. The label set is unique as the pod name is also send as a label.

**Expected behavior**
Ingester doesn't throw `out of order` errors.

**Environment:**
 - Kubernetes
 - jsonnet

**Screenshots, Promtail config, or terminal output**

From ingester:
```
[ingester-666d8c9f6c-xx4qr] level=warn ts=2020-01-03T04:32:54.802566357Z caller=grpc_logging.go:37 method=/logproto.Pusher/Push duration=2.135351ms err="rpc error: code = Code(400) desc = entry with timestamp 2020-01-03 11:07:09.429656298 +0000 UTC ignored, reason: 'entry out of order' for stream: {app=\"app\", container_name=\"app\", filename=\"/var/log/pods/default_app-deployment-d47cfd8b5-dqd8q_e6404383-21ae-11ea-a3cd-42010a8e00b8/app/0.log\", instance=\"app-deployment-d47cfd8b5-dqd8q\", job=\"default/app\", namespace=\"default\", pod_template_hash=\"d47cfd8b5\", stream=\"stdout\"}
```

From promtail logs the same error is always preceded by a `context deadline exceeded` error.
```
level=warn ts=2020-01-03T04:32:55.411390868Z caller=client.go:226 component=client host=<loki-hostname> msg="error sending batch, will retry" status=500 error="server returned HTTP status 500 Internal Server Error (500): rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error ts=2020-01-03T04:32:55.556252986Z caller=client.go:231 component=client host=<loki-hostname> msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry with timestamp 2020-01-03 04:32:15.456325034 +0000 UTC ignored, reason: 'entry out of order' for stream: {app=\"<appname>\", container_name=\"<container_name>\", filename=\"/var/log/pods/default_app-deployment-85b54e4rr5-hfj2q_7a03da5c-21aa-11ea-b731-42010a8e022c/wormhole/0.log\", instance=\"app-deployment-85b54e4rr5-hfj2q\", job=\"default/app\", namespace=\"default\", pod_template_hash=\"85b54e4rr5\", release=\"stable\", stream=\"stdout\"},"
```

At the same time from the distributor:
```
level=warn ts=2020-01-03T04:32:55.402576346Z caller=logging.go:49 traceID=6c078d5a0d5303b msg="POST /api/prom/push (500) 5.907360345s Response: \"rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Connection: close; Content-Length: 24425; Content-Type: application/x-protobuf; User-Agent: Go-http-client/1.1; X-Forwarded-For: <>; X-Forwarded-Proto: https; X-Scope-Orgid: 1; "
level=warn ts=2020-01-03T04:32:56.201830727Z caller=logging.go:49 traceID=52c0c88559586ac3 msg="POST /api/prom/push (500) 6.991604004s Response: \"rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Connection: close; Content-Length: 40812; Content-Type: application/x-protobuf; User-Agent: Go-http-client/1.1; X-Forwarded-For: <>; X-Forwarded-Proto: https; X-Scope-Orgid: 1; "
```
Redeployed all the components as well just make sure to get rid of the old hash but the issue still persists. 

Does the timeout error in promtail indicate something else or does it always precede an out of order error?

The distributor currently receives about 100k log lines per second, `out of order` issues are found for the apps that contribute to more than 50% of these logs.

**Comment by pstibrany** [comment]
It looks to me as those out-of-order errors are result of first request failing, and then retrying.

On retry, it sends same data – but if this data was received before and partially processed, then getting the same data again would indeed produce out of order error, because timestamps are less or equal than seen previously.

It might be worth looking into those “context deadline exceeded” problems, and to fix those. Unfortunately I don’t see any configurable timeouts in promtail, related to sending data.

It seems that your distributor says that requests take around 6 seconds, which is a lot. Any idea why that would be the case?

**Comment by anishlal** [comment]
Not exactly sure but I've increased the number of ingester and distributor replicas to 10 which seems to have reduced the out of order errors drastically. Earlier ingester had 7 replicas, consumed around 2-3GB of memory each and 0.5 CPU, distributor had 6 replicas which consumed around .8 - .9 CPU (limit is 1) and 300 - 500 MB memory. The limits set for these pods was never reached and I haven't noticed any resource contention. Now each distributor replica consumes only .5 - .6 CPU and each ingester replica consumes 1.2 - 1.5 GB of memory. Lines received by distributor reduced from 16k/sec to 10k/sec. The distributor latency has also reduced by half. Since the limits for either distributor or ingester was not reached in the first place any idea why this would result in out of order errors?

It is mentioned in the cortex running guide that 

> Each 100,000 samples/sec arriving takes 1 CPU in distributors

which I assume applies for prometheus. Is there some kind of rule of thumb like this for Loki as well? And should the number of distributor and ingester replicas be the same for any reason?

**Comment by anish-lal** [comment]
Not exactly sure but I've increased the number of ingester and distributor replicas to 10 which seems to have reduced the out of order errors drastically. Earlier ingester had 7 replicas, consumed around 2-3GB of memory each and 0.5 CPU, distributor had 6 replicas which consumed around .8 - .9 CPU (limit is 1) and 300 - 500 MB memory. The limits set for these pods was never reached and I haven't noticed any resource contention. Now each distributor replica consumes only .5 - .6 CPU and each ingester replica consumes 1.2 - 1.5 GB of memory. Lines received by distributor reduced from 16k/sec to 10k/sec. The distributor latency has also reduced by half. Since the limits for either distributor or ingester was not reached in the first place any idea why this would result in out of order errors?

It is mentioned in the cortex running guide that 

> Each 100,000 samples/sec arriving takes 1 CPU in distributors

which I assume applies for prometheus. Is there some kind of rule of thumb like this for Loki as well? And should the number of distributor and ingester replicas be the same for any reason?

**Comment by anish-lal** [comment]
@pstibrany The out of order errors seems to be directly proportional to the distributor -> ingester append failure rate. Looks like append failures causes logs to be send again that results in out of order error. Is there any way we can determine why the appends are failing? 

Increasing the ingester and distributor replicas reduces the append failures but given the free resources in existing nodes, which the ingester/distributor pods can utilise, it seems to be a wastage of resources.

**Comment by pstibrany** [comment]
> Is there any way we can determine why the appends are failing?

I would look at logs from promtail, distributors or ingesters.
