### ISSUE TITLE
bloomplanner queue_length metric disappears

### ISSUE THREAD

**Issue by nathwill** [grafana/loki#15295]
**Describe the bug**
bloom-planner quits reporting the queue_length metric when the value is zero. this causes periods with no samples, which prevents it from being useful in autoscaling. (metrics api returns 404, causing HPA to freeze with last measured value, blocking builder scale-down).

**To Reproduce**
1. Start Loki 3.3 with bloom planner/builder enabled
2. observe that loki_bloomplanner_queue_length is missing in planner metrics endpoint
3. wait for a build iteration to start
4. observe the metric is present with a non-zero value
5. wait for build iteration to finish
6. observe that the metric is missing
7. despair

**Expected behavior**
the metric is initialized with a zero value on start and is retained with a zero value when the queue is empty.

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

**Comment by chaudum** [comment]
The behaviour you describe is by intention. The queue metric has the label `user` which potentially has very high cardinality when running Loki in multi-tenant mode. In order to minimize the cardinality, metrics from "inactive" users are deleted.

See 
https://github.com/grafana/loki/blob/main/pkg/bloombuild/planner/queue/queue.go#L76-L79
and
https://github.com/grafana/loki/blob/main/pkg/queue/metrics.go#L37-L41

The better metric for auto-scaling bloom builders is `loki_bloomplanner_inflight_tasks` or `loki_bloombuilder_processing_task`.

Alternative you can use

```
loki_bloomplanner_queue_length{} or vector(0)
```

**Comment by nathwill** [comment]
yeah i ended up using loki_bloomplanner_inflight_tasks, but afaik that includes what's already being processed by builders, so i figured queue_length would be a better metric. we tried using `loki_bloomplanner_queue_length{} or vector(0)` as the metricsQuery before reporting, but prometheus-adapter wasn't ever reaching the metricsQuery because the seriesQuery was returning no samples. we might try using `{__name__="loki_bloomplanner_queue_length"} or vector(0)` as a seriesQuery, but for now at least we're happy with the performance of loki_bloomplanner_inflight_tasks. thanks.
