### ISSUE TITLE
Support syslog-ng

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#153]
https://twitter.com/PCzanik/status/1074996519638568961

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/36#TOPIC-1094599

https://www.syslog-ng.com/community/b/blog/posts/bulk-mode-message-sending-to-elasticsearch-with-syslog-ng-http-destination

**Comment by madmaze** [comment]
Would you envision this capability to be built into loki itself or an external translator/forwarder?

**Comment by tomwilkie** [comment]
Haven't given it much thought TBH!  We're looking to add fluend support, so perhaps that can act as the translator?

**Comment by madmaze** [comment]
I'll prototype a translator proof-of-concept in the coming days, but I think ultimately it would be nice to have  ingest modules/plugins.

**Comment by cypherfox** [comment]
Any update on this? Can I see the translator code? Never mind if it is rough. 
I just want to get the other ducks in line by deciding where to use syslog(-ng) and where to look for alternatives when logging non-k8s sources.

**Comment by daixiang0** [comment]
@tomwilkie hi, any process about this?

**Comment by odormond** [comment]
It's currenlty impossible to ingest lines from syslog properly even with pipeline stages without reconfiguring syslog itself.
The problem is that the default timestamp at the beginning of the lines looks like `Jun 20 14:54:51` which even with a proper `timestamp` stage format will be parsed as `time=0000-06-20T
14:54:51Z` which will fail to encode: `msg="error encoding batch" error="timestamp: &types.Timestamp{Seconds: -62152391109,\nNanos: 0,\n} before 0001-01-01"`

**Comment by pbadenski** [comment]
Is this possible now considering https://github.com/grafana/loki/pull/760 has been merged?

**Comment by eagle1981** [comment]
+1

**Comment by cyriltovena** [comment]
With our new fluentbit output plugin, it should be possible to capture syslog via this official input plugin https://fluentbit.io/documentation/0.12/input/syslog.html
