### ISSUE TITLE
Allow specifying multiple configuration files in priority order

### ISSUE THREAD

**Issue by shughes-uk** [grafana/loki#1723]
We deploy loki as part of our application, and currently have no way set up loki with defaults that make sense for our app, while also providing a method for individual customers to override certain settings according to their needs.

Customers can change our 'sensible defaults file', but we either need to write a complex configuration migration script to preserve their changes each time we upgrade, or we blow away their changes. It would be nice if like docker-compose we could specify multiple config files that are loaded in order, with the last file loaded taking priority.

**Comment by cyriltovena** [comment]
Have you considered an init container with jsonnet merging since this seems more like a configuration problem ?

Loading multiple configuration files seems to be a fine idea, but I don't think we'll have the bandwidth right now to work on this, of course contributions are more than welcome and we can assist you there.

**Comment by shughes-uk** [comment]
We're on just docker and init containers seem to be a kube thing so we can't use them unfortunately. I'll see if i can find someone decent at Go to submit a PR.

**Comment by cyriltovena** [comment]
In the meantime you could run something to merge default+custom config in the entry point of docker by reusing our image.

I suggested jsonnet but whatever works. There's a lot of tool out there to merge yaml.
