### ISSUE TITLE
Loki query returns empty

### ISSUE THREAD

**Issue by nsherry4** [grafana/loki#1772]
**Describe the bug**
`/loki/api/v1/query` always returns no data `{"status":"success","data":{"resultType":"streams","result":[]}}` but other URLs like `/loki/api/v1/query_range` or `/api/prom/query` return data properly.

**To Reproduce**
1. Installed and started Loki v1.3.0
2. Waited for data to be populated from logs
3. Query: seems to be anything aimed at this specific call

**Expected behavior**
`/loki/api/v1/query` returns data like other API calls do.

**Environment:**
 - Infrastructure: systemd/journald log fetching, Loki 1.3.0 (also happens in 1.2.0)
 - Deployment tool: manual local install, promtail installed via custom ansible config.

**Screenshots, Promtail config, or terminal output**
Example `/loki/api/v1/query`
```
# curl -G -s  "http://localhost:3100/loki/api/v1/query" --data-urlencode 'query={job="systemd_logs"}' --data-urlencode 'limit=1'
{"status":"success","data":{"resultType":"streams","result":[]}}
```
But `/loki/api/v1/query_range`
```
# curl -G -s  "http://localhost:3100/loki/api/v1/query_range" --data-urlencode 'query={job="systemd_logs"}' --data-urlencode 'limit=1'
{"status":"success","data":{"resultType":"streams","result":[{"stream":{"host":"<HOSTNAME>","job":"systemd_logs","priority":"6"},"values":[["<LOG CONTENTS>"]]}]}}
```
And `/api/prom/query`
```
# curl -G -s  "http://localhost:3100/api/prom/query" --data-urlencode 'query={job="systemd_logs"}' --data-urlencode 'limit=1'
{"streams":[{"labels":"{host=\"<HOSTNAME>\", job=\"systemd_logs\", priority=\"6\"}","entries":[{"ts":"2020-03-03T17:02:19.947479Z","line":"<LOG CONTENTS>"}]}]}
```

**Comment by cyriltovena** [comment]
Hey @nsherry4,

I think (I'm not fully sure since I don't have your data) there is no issue here but a lack of documentation on how the instant endpoint `/loki/api/v1/query` works.

By default (if you don't provide a time like you did in the example) the instant query endpoint will query for logs at the current nanoseconds and look back using the `max_look_back_period` configuration (by default 30 seconds, https://github.com/grafana/loki/blob/master/pkg/logql/engine.go#L65). So the last 30 seconds from now, this is configurable as you can see.

On the other hands, both `/loki/api/v1/query_range` and `/api/prom/query` returns the last hour by default. 

I think this could explain why you're not seeing data. You could change that config to 1h if you want to have the same behaviour see below a helm example.

```yaml
config:
....
  querier:
    engine:
      max_look_back_period: 1h
  ingester:
....
```

Feel free to close if that answer the question.

**Comment by nsherry4** [comment]
So if I _do_ provide a time, it will still look backwards from that point for at most `max_look_back_period` (less with a limit set)?

**Comment by cyriltovena** [comment]
Yes correct. This is the exact same behavior as Prometheus.

**Comment by nsherry4** [comment]
Okay, thanks. Sounds like I want to use the `query_range` API call instead to get logs from an unbounded time interval?

**Comment by cyriltovena** [comment]
> unbounded time interval

Query range allows you to choose a start and end timestamp (ns) but not unbounded.

**Comment by nsherry4** [comment]
Okay, thank you for your time.
