### ISSUE TITLE
Port change to 8080 broke docker-compose example

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/loki#1832]
**Describe the bug**
Default Port was changed from `http_listen_port: 3100` to `http_listen_port: 8080` in #1823 
This breaks the [`docker-compose.yaml`](https://github.com/grafana/loki/blob/master/production/docker-compose.yaml) example, which is still using 3100.
You cannot connect to loki from grafana if you use compose and wonder why.

Also several docs still state `3100`, as does the placeholder in grafana add datasource ui.

**To Reproduce**
Use the linked `docker-compose.yaml` with current docker image of `grafana/loki`
You won't be able to connect if you try 3100.

Is the future default port of loki `8080` ?

**Comment by cliv** [comment]
Specifically, it looks like https://github.com/grafana/loki/pull/1823/commits/cde1ad84b7118846f7b61f24768753d3a899ed26#diff-17af4cf9a6bbf96dc43ad4544bfad96bL4 was the breaking change.  

If one was running with the default configuration file (/etc/loki/local-config.yaml) specified in /production/docker-config.yml, loki was never running on port 80 in the first place - so why change it?  Why use 8080 as the default in the first place instead of 3100?

**Comment by wardbekker** [comment]
@cyriltovena The port change in cmd/loki/loki-local-config.yaml from 3100 => 8080 seems not needed? Bunch of config still assumes loki to be available on port 3100, like promtail default config here: https://github.com/grafana/loki/blob/master/cmd/promtail/promtail-local-config.yaml#L9

**Comment by cyriltovena** [comment]
We made a change in the docker image to run loki as non-root users. This has caused us trouble in our environment because 80 can't be bound without root.

This is why we made changes to the port binding in the docker image.

**Comment by cyriltovena** [comment]
I'll make it 3100 everywhere.
