### ISSUE TITLE
Please document ____journal__* labels

### ISSUE THREAD

**Issue by rgarrigue** [grafana/loki#2048]
**Is your feature request related to a problem? Please describe.**

I'm missing documentation of which label I can get from Promtail's journal scraping. Searching the repo I found __journal__systemd_unit and __journal__hostname, but are there more ? 

**Describe the solution you'd like**

Update https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#journal_config with the same kind of listing there's around https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#node

**Comment by patrickjahns** [comment]
@rgarrigue 
I had a look at the code - promtail uses [coreos/sdjournal](https://github.com/grafana/loki/blob/f5b9cffc2eaed5fe49d8f54d9cf304d618e82ad9/pkg/promtail/targets/journaltarget.go#L24) 
If you look into sdjournal - you'll find the [definition of fields](https://github.com/coreos/go-systemd/blob/master/sdjournal/journal.go#L317-L356)

Combining this with the remapping promtail does:
https://github.com/grafana/loki/blob/f5b9cffc2eaed5fe49d8f54d9cf304d618e82ad9/pkg/promtail/targets/journaltarget.go#L324-L326

Examples
- `_SYSTEMD_UNIT` will become `__journal__systemd_unit`
- `_HOSTNAME ` will become `__journal__hostname`

A little more background on the fields is available at https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html

I am a bit uncertain if it's safe to document them all, as it seems that for example "unsafe fields" are "user provided" and might not exist. Also for the "safe" fields I am not sure if every log entry would contain them.
I guess one would need to test what happens if fields are not found for (re)-labelling?

**Comment by rfratto** [comment]
It'd be useful for us to just add the link to the standard fields from that URL @patrickjahns shared. But the docs should also make it clear that:

1) Each message from the journal may have a different set of fields
2) Software may write an arbitrary set of custom fields for their logged messages. 

From what I remember, relabeling a field from the journal that isn't present for a specific message ends up treating it as an empty string and your label will be given an empty value. I'd have to write a test to double-check, though.

This is totally something we should be documenting but I won't have time to take a look at it for a few weeks, but I'll take a shot at it as soon as I'm able to.

**Comment by owen-d** [comment]
I think this can be solved via documentation, including a link to the std fields.

**Comment by takanabe** [comment]
Let me take this since I will test a systemd journal scraping 📝

**Comment by brolaugh** [comment]
I find this to still be a problem.

**Comment by arcenik** [comment]
PR is here https://github.com/grafana/loki/pull/11888

**Comment by robinpecha** [comment]
Quick help:
https://github.com/grafana/loki/pull/11888/files
#### Available Labels
Labels are imported from systemd-journal fields. The label name is the field name set to lower case with **__journal_** prefix. See the man page [systemd.journal-fields](https://www.freedesktop.org/software/systemd/man/latest/systemd.journal-fields.html) for more information.

For example:

| journal field      | label                   |
|--------------------|-------------------------|
| _HOSTNAME          | __journal__hostname     |
| _SYSTEMD_USER_UNIT | __journal__systemd_unit |
| ERRNO              | __journal_errno         |

In addition to **__journal_priority** (imported from **PRIORITY** journal field, where the value is an integer from 0 to 7), promtail adds **__journal_priority_keyword** label where the value is generated using the **makeJournalPriority** mapping function.

| journal priority | keyword |
|------------------|---------|
| 0                | emerg   |
| 1                | alert   |
| 2                | crit    |
| 3                | error   |
| 4                | warning |
| 5                | notice  |
| 6                | info    |
| 7                | debug   |
