### ISSUE TITLE
Make Loki log Labels available in Grafana Table Visualization 

### ISSUE THREAD

**Issue by LokiNoob** [grafana/loki#2222]
**Is your feature request related to a problem? Please describe.**
It would be great if we could use the Log Labels associated with a syslog message as columns in a table visualization when building a dashboard from the Loki Data Source. 

**Describe the solution you'd like**
Log Labels are available as individual columns in the table visualization. 
Log Labels: 
![Loki_log_labels](https://user-images.githubusercontent.com/66995779/84752149-0d50b580-afc6-11ea-82c9-da03066ae890.JPG)

Available columns: 
![Grafana_visualization](https://user-images.githubusercontent.com/66995779/84752188-1a6da480-afc6-11ea-8785-999da9f924c7.JPG)

**Comment by auricom** [comment]
Hello,

I would love to see this feature. Or maybe we need to "convert" labels into Parsed fields ?
However it seems that we cannot create a table without the "message" column.

Maybe loki is not designed to have visualization on dashboards, but to ease the log checking when debugging, using labels ?

**Comment by cyriltovena** [comment]
We should transfer this issue to grafana.

**Comment by elserhumano** [comment]
I want to use Grafana + Loki + Promtail with Apache logs for forensic analysis. My goal to somehow replace the parsed fields with a label.
The reason is that when Promtail sends all the records to Loki, the date in "ts" as the parsed field is my current date and not the date of the row of the record.
I want to keep the record date and for that reason, I get it on a tag.
But when I try to make a dashboard it is crazy because all events happen at the same time and with today's date and not at the moment when this actually happened.
Is there a way to do this?

**Comment by sandstrom** [comment]
@cyriltovena Do you know if this was transferred to grafana? Would be an awesome feature 😄

**Comment by mkwiecinski** [comment]
@RamblingCookieMonster +1, I am coming from Azure Monitor and having hard time to replicate my querying workflow and be able to see at the same time a table view with key variables extracted from the JSON for a quick visual inspection, re-ordering etc and - just one click away - the original, nicely formatted full JSON with details
