### ISSUE TITLE
Development in Goland

### ISSUE THREAD

**Issue by tivvit** [grafana/loki#2403]
Is anybody using Goland for Loki development? 

I have a problem configuring that, because Goland is reporting 
```
go list -m: can't compute 'all' using the vendor directory
	(Use -mod=mod or -mod=readonly to bypass.)
```

I see in the `Makefile` that Loki is built with `-mod=vendor` but I am not able to force this flag to Goland.

thanks in advance.

**Comment by cyriltovena** [comment]
@pstibrany and @pracucci are.

**Comment by slim-bean** [comment]
I am as well, but can't say i've seen this issue.

![image](https://user-images.githubusercontent.com/10332331/88302516-ef1c5a80-ccd3-11ea-8074-05d7269e16ee.png)

Are my settings.

I can say I do have problems using the built in goland terminal because it sets some environment variables related to vendoring which cause me errors and i've worked around this by just using a separate terminal..

**Comment by tivvit** [comment]
I am building it separate terminal too but I am missing IntelliSense features.

![Screenshot from 2020-07-23 17-22-05](https://user-images.githubusercontent.com/3392931/88304873-1c373000-cd09-11ea-9ac3-045c8c887baf.png)

```
GoLand 2019.1.3
Build #GO-191.7479.32, built on May 30, 2019
...
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.7.9-200.fc32.x86_64
```
@

**Comment by tivvit** [comment]
Created issue for Goland https://youtrack.jetbrains.com/issue/GO-9704

**Comment by pracucci** [comment]
> GoLand 2019.1.3

I'm running GoLand 2020.1 and I haven't seen this issue. Have you tried to upgrade it?

**Comment by tivvit** [comment]
thx a lot @pracucci it fixed it for me. I thought I have the latest version :facepalm:.
