### ISSUE TITLE
Error when using Minio with Consul Connect Sidecar

### ISSUE THREAD

**Issue by reidlai** [grafana/loki#2451]
**Describe the bug**
If i use minio with S3 protocol directly in MinIO, everything works fine.  But I got the following error when using Consul Connect sidecar

vel=error ts=2020-07-30T09:07:12.225470277Z caller=flush.go:179 org_id=fake msg="failed to flush user" err="RequestError: send request failed\ncaused by: Put https://localhost.:9000/loki/fake/646f51dd9d5863ad%3A1739ead28da%3A1739ef5ccfd%3A4b085fb2: dial tcp: lookup localhost. on 10.96.0.10:53: server misbehaving" 

**To Reproduce**
1. Install Consul Connect in minikube
2. Install Minio
3. Make sure Loki is working fine with Minio without Consul Connect Inject
4. Add consul connect injection pod annotation in Loki statefulset
5.  Once loki containers retart, you will see the error

**Expected behavior**
I am expecting everything works fine if I use Minio directly or thru sidecar.  Suppose it is transparent.

**Comment by slim-bean** [comment]
I'm not sure this is an issue with Loki? If everything works fine before you add the Consul Connect Sidecar it feels the issue is more with that sidecar which I'm afraid I'm not really familiar with.

From that error message it sounds like this sidecar is trying to intercept DNS requests and fails to resolve localhost? It seems like this may be more of a question for the Consul Connect project?
