### ISSUE TITLE
Bug: Promtail log is reporting error for non-existent symlink

### ISSUE THREAD

**Issue by c0ffeec0der** [grafana/loki#2513]
**Describe the bug**
Promtail log is reporting error for non-existent symlink

Sample error log

level=error ts=2020-08-15T11:01:19.658356919Z caller=filetarget.go:283 msg="failed to tail file, stat failed" error="stat /var/log/pods/kube-system_kube-apiserver-docker-desktop_2966bdea771eade42b079889c75cf17e/kube-apiserver/2.log: no such file or directory" filename=/var/log/pods/kube-system_kube-apiserver-docker-desktop_2966bdea771eade42b079889c75cf17e/kube-apiserver/2.log

File 2.log is pointing to

lrwxrwxrwx 1 root root 165 Aug 15 09:07 2.log -> /var/lib/docker/containers/52b0d469a5ba5e6f1124d67c0b91308151f34fc9df5183c80b24c712bb52de32/52b0d469a5ba5e
6f1124d67c0b91308151f34fc9df5183c80b24c712bb52de32-json.log

When perform "cat" to target file json.log

cat: /var/lib/docker/containers/52b0d469a5ba5e6f1124d67c0b91308151f34fc9df5183c80b24c712bb52de32/52b0d469a5ba5e6f1124d67c0b91308151f34fc9df5183c80b24c712bb
52de32-json.log: No such file or directory

The pod kube-system_kube-apiserver-docker-desktop is up and running. In grafana explorer, promtail return logs for the pod. They are in file 0.log

**To Reproduce**
1. Started Loki (1.5)
2. Started Promtail (1.5)
3. Query: `{pod="loki-promtail-[input your pod id]"}|="error"`

**Expected behavior**
no error as this is fresh run

**Environment:**
 - Infrastructure: Docker desktop with kubernetes 1.16.5
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Error

![image](https://user-images.githubusercontent.com/64681762/90311400-b2cfc900-df24-11ea-98ac-44cd99ddf4ad.png)

Sample the api server error, but it is working fine

![image](https://user-images.githubusercontent.com/64681762/90311439-2d98e400-df25-11ea-9d49-818473e1b21c.png)

Result for cat 2.log and 3.log, 0.log will show result as the previous screenshot

![image](https://user-images.githubusercontent.com/64681762/90311533-f840c600-df25-11ea-81a5-e0d0ba17d819.png)

**Comment by slim-bean** [comment]
This is a duplicate of #429 which I see you originally commented on and then instead opened a new issue.  It's bad practice to create a new issue when an existing issue for the exact problem exists.

The reasons the old issue went stale and closed and the reason I will likely close this issue: I do not consider this is not a bug in promtail. The problem is either in docker or kubernetes not cleaning up links to files properly.

Promtail is enumarting the files in the directory, finds a symlink, and follows that symlink to a non existing file.

We don't have any control over the creation or removal of these symlinks as such there isn't anything we can directly do about the source of the problem itself: a broken symlink left behind by docker or kubernetes.

That being said, could there be a feature request to handle this differently, absolutely.  What we should do with it, I'm not exactly sure.  There are other reasons why this is a useful message to log at error level, so I'm reluctant to move it to debug. 

A rate limiting logger would be a nice solution but is not something we have currently.

In the meantime it would be possible to drop these messages in promtail, in 1.5.0 you can use the [match](https://grafana.com/docs/loki/latest/clients/promtail/stages/match/) stage and this gets a bit easier in 1.6.0 with the addition of the [drop stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/) which would let you write a regex to match that error and drop it from your logs.

**Comment by c0ffeec0der** [comment]
Hello,

Yes you are right. I did comment on #429. However, this happen after a clean reset of the kubernetes. where you did not experience based on comment https://github.com/grafana/loki/issues/429#issuecomment-502453125

#429 assumed the root cause is from docker daemon not cleaning up symlink, https://github.com/grafana/loki/issues/429#issuecomment-520859169.

I created this issue because it still appears after a clean reset. Sorry if I didn't mention this in the first place. And it occurs only on some pods (in this case kube-apiserver, kube-controller, kube-scheduler). The other pods are doing ok. 

Is this the still the same issue as #429 ? 

It's just so confusing because a fresh install, immediately creates error log.

I was also thinking about dropping while scrapping the log as workaround (assuming the concept with prometheus because I haven't gone into detail with promtail). It would clean the log before entering loki and chunk store. However, promtail own log file would still suffer

Question : Why not upon detection of "err no such file or directory", delete the file in process instead of showing message. Is there another scenario where the detection is needed?

**Comment by slim-bean** [comment]
> I created this issue because it still appears after a clean reset. Sorry if I didn't mention this in the first place. And it occurs only on some pods (in this case kube-apiserver, kube-controller, kube-scheduler). The other pods are doing ok.
> Is this the still the same issue as #429 ?

This is a fair question and opening another issue is ok if you aren't sure if an issue is a duplicate, but I think it's best to always reference as much context including linking any related issues you found, it saves time for all of us and helps more quickly get to the root of the problem.

BTW, your writeup is very good and the supporting information and testing you did are very helpful! I was confused because I got an email that you had commented on 429 then I saw this new issue and thought I was going crazy trying to figure out why I got an email for an existing issue but when I sorted the issue list by recent activity nothing showed up for 429.  Sorry for sounding a bit cranky earlier but it was a bit frustrating trying to figure out what was going on.

To answer your question if this is the same as #429, yes I believe it is, or put another way.  I still think this issue has nothing to do with promtail.  I spent some time searching and found https://github.com/kubernetes/kubernetes/issues/52172 which was linked by several other issues: https://github.com/kubernetes/kubernetes/issues/45911 seems very related.
 
It seems the bug here is in kubelet and unfortunately it doesn't seem like there is any likely fix coming soon.

> Question : Why not upon detection of "err no such file or directory", delete the file in process instead of showing message.

This is potentially possible, however it scares me to think about having promtail delete files 😮 I would really worry about edge cases that we don't think through properly where we delete log files or symlinks which we really shouldn't! (for example it already feels like there would be a race between when the file is created and the symlink is created, what happens if the symlink is created before the file and promtail finds the symlink before the file is created and we delete it?)

>  Is there another scenario where the detection is needed?

Yes there are several, the most common is promtail having read permissions on the symlink, but NOT having read permissions on the directory or file pointed to by the symlink.  


I think the best solution here is to add a `drop` entry to the pipeline for this message, I'm extremely reluctant to hide the message or change the log level as there are other fixable problems where this message is thrown and would prefer to fall on the side of being overly verbose to allow people to easier troubleshoot problems.

**Comment by c0ffeec0der** [comment]
Hello,

Thank you for the explanation. I think I understand now why you would like to leave the symlink as is. It seems promtail is copying all the actual log files and symlinks from the containers; keep it as original as is, and then iterate one by one.

I am still playing with the `drop` function in version 1.6.0, so far no luck.. I'll try reading the docs and update when I found the solution. 

Thank you

**Comment by c0ffeec0der** [comment]
Hello

After some reading on the docs,

It seems like to add 'drop' function would be to add below code in pipeline_stages

      - drop:          
          expression: ".*(error).*(filetarget.go).*(no such file).*"

for existing scraping job:

1. kubernetes-pods-name
2. kubernetes-pods-app
3. kubernetes-pods-direct-controllers
4. kubernetes-pods-indirect-controller
5. kubernetes-pods-static

The reason being is that these jobs are created so that the subsequent jobs covered the relabeling process so that it does not create duplicate entry. (i.e job 1 detect by __meta_kubernetes_pod_label_name, job 2 skip if __meta_kubernetes_pod_label_app has value and detect by __meta_kubernetes_pod_label_app)

If you agree on this, we could modify file

https://github.com/grafana/loki/blob/master/production/helm/promtail/values.yaml

for section pipelineStages. Let me know and I will create a PR
