### ISSUE TITLE
Distributed/Microservices Loki Helm chart

### ISSUE THREAD

**Issue by Whyeasy** [grafana/loki#2529]
**Is your feature request related to a problem? Please describe.**

Currently there is a Helm chart for Loki in a single instance mode. I wanted to run Loki in a microservice/distributed way. As we were using Jsonnet before, but migrated to Helm charts for simplicity. So I took the Jsonnet production files and transformed it in to a Helm chart. I was hoping if more people were interested in the chart.

**Describe the solution you'd like**

I created a Helm chart for my needs and it's far from done to configure all options. This is what I have so far and maybe we can expand it:  https://github.com/whyeasy/helm-charts/tree/master/charts/distributed-loki

**Comment by cyriltovena** [comment]
I suggest we create a special repo for community work like this and give that away to the community.

**Comment by unguiculus** [comment]
Linking #2593

**Comment by jemag** [comment]
I may be mistaken on this as I am pretty new to Loki, however it seems like the recommended setup for a production scenario is to run Loki in microservices mode. 

It also seems like Helm is currently not supporting microservices mode and also not supporting the scaling of statefulsets.

Given that Helm is more widely adopted than Ksonnet, wouldn't it make sense to have the helm chart be able to deploy a highly available production setup? If the time required to maintain various highly available production installation methodologies is significant, I believe a  greater percentage of the user base would like to see that time invested in Helms rather than Ksonnet.

**Comment by cyriltovena** [comment]
Yes to all of this, but we’re not using helm internally and having a chart is something that takes time to support and maintain, and we prefer to deliver features for now.

This is open source and we hope the community can fill the gap, this is what the linked issue is about and we’re all in !

We just need to figure how, so yes again you’re are right, you’re all welcome to get involved in this.

**Comment by Pluies** [comment]
(For future reference / peeps who googled it and ended up here: this chart is now available at https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed )
