### ISSUE TITLE
If Tanka is the most recommended install method, why does it go against multi-tenancy?

### ISSUE THREAD

**Issue by charandas** [grafana/loki#2538]
**Is your feature request related to a problem? Please describe.**

I am unable to understand the reasoning behind defaulting the OrgId header value to 1 [here](https://github.com/grafana/loki/blob/master/production/ksonnet/loki/gateway.libsonnet#L46).

**Describe the solution you'd like**
I am enabling auth in my config, and even fronting my nginx with an ingress controller that is setting tenant header correctly, before proxying nginx. Can we make it configurable in gateway.libsonnet by any chance, or do I have to override the whole configmap somehow in order to just no-op that one line?

**Comment by owen-d** [comment]
The gateway is included primarily as a convenience and isn't necessary. Since you're already setting auth in some manner, feel free to remove the gateway from your deployment entirely. Once you do that, it should work as you expect :)

That being said, I definitely agree it's unexpected to have that hardcoded.

**Comment by charandas** [comment]
Sounds good @owen-d. Thanks!
