### ISSUE TITLE
Add a namespaceOverride option for Helm deployment

### ISSUE THREAD

**Issue by jgardner04** [grafana/loki#2670]
**Is your feature request related to a problem? Please describe.**
When deploying the loki-stack chart as a dependent chart, Helm limitations require that it be deployed into the same namespace as my primary application. I am trying to have the loki-stack deployed into a separate namespace from my primary application. 

**Describe the solution you'd like**
I'd like to see an option for namespaceOverride where I could define the namespace for the chart allowing me to control the location of the sub chart deployment. 

It appears that this is already a value in the grafana chart.

**Describe alternatives you've considered**
The alternative would be to deploy the Loki stack as a separate deployment from my main application.

**Comment by jkremser** [comment]
related issue - when loki got upgraded to the new architecture w/ all the bells and whistles where everything is a micro-service, the simplest way of using the object storage is using the minio sub-chart. However, this guy doesn't have support for `namespaceOverride ` knob on their helm chart and probably won't have it since the repo got archived in April.

So currently minio takes the value from `{{ .Release.Namespace }}` :/
