### ISSUE TITLE
Wrong parameter names in Loki example

### ISSUE THREAD

**Issue by huikang** [grafana/loki#2684]
Hi, I am new to Loki. When I played with its local deployment, I found an inconsistent description of a parameters
**Describe the bug**

1. https://github.com/grafana/loki/blob/02540703c86afeca67d2533ee1fbb4a59d92fa44/cmd/loki/loki-local-config.yaml#L8

Should the above be "addr: 127.0.0.1" to be consistent with the what in the help message: `-ingester.lifecycler.addr string 	IP address to advertise in consul.`?

2. My understanding is that the ingesters' ring is also supported in etcd. If so, why the above help message only mentions `consul`?

Thanks.

**Comment by slim-bean** [comment]
I'm sure this because consul was added first and etcd support was added later and nobody updated the help text.

This message actually comes out of the cortex code here: https://github.com/cortexproject/cortex/blob/c8f5e172c41f62fbc00b7783f109517bec1e868f/pkg/ring/lifecycler.go#L101

Could you please open an issue in the cortex repo, or even better a PR to improve the help text?

**Comment by huikang** [comment]
- I submitted a PR to cortex: https://github.com/cortexproject/cortex/pull/3246
- How about my first question regarding the sample configuration file?
Thanks.
