### ISSUE TITLE
Limits metrics queries cardinality.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#2823]
With the new LogQL extensions we can now implicitly extract many labels.

Specially with logfmt and json.

We should add a way to via configuration:
- limit the maximum amount of labels per unique series and unique total series.

Questions ?
- Where should this be checked, within ingesters ? queriers ? frontend ? all of them ?

**Comment by owen-d** [comment]
I think you _have_ to check them wherever we run parsers because the label set is only available after parsing. 

I also think it'd be helpful to be able to specify a strategy at the query level such that you can either error the whole query or drop any offending lines (similar to using `__error__` in logql). WDYT?

**Comment by cyriltovena** [comment]
I will start with errors for now, no dropping, we can do that later since I think it's more complex to craft.
