### ISSUE TITLE
Update auth_token_bearer dynamically from file

### ISSUE THREAD

**Issue by ecusnir** [grafana/loki#2998]
**Is your feature request related to a problem? Please describe.**
In order to ensure authentication between fluentd and Loki, we would like to use OAuth with dynamically generated bearer tokens. Loki's fluentd plugin already supports adding the bearer_token from file to the Authorization header, but it only covers the[ long-lived token scenario](https://github.com/grafana/loki/blob/master/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L116). Is it possible to implement a strategy similar to the one used by prometheus? https://github.com/grafana/loki/blob/fd451d97f4d6a51ea1f67c1959def077ffb78ee4/vendor/github.com/prometheus/common/config/http_config.go#L189

**Describe the solution you'd like**
Dynamically update the bearer token in Authorization header with the latest value from `bearer_token_file` to support short-lived token schema.

**Comment by ecusnir** [comment]
This issue is not stale. Dynamically updating the bearer token is still needed.

**Comment by owen-d** [comment]
We'd accept PRs for this, but likely won't be prioritizing it ourselves.

**Comment by marekasf** [comment]
Prometheus added support for oauth2 config recently.
https://github.com/prometheus/prometheus/pull/8761

Is this sth which can be used in promtail?

**Comment by arempter** [comment]
I did a quick test where I've updated loki dependencies with latest prometheus (v2.27.1). I had to also update k8s.io/client-go v0.21.1, since some signatures has changed. There were also some indirect updates of dependencies...

With that I was able to use oauth2 config with promtail.

@owen-d question is, if from Loki perspective such dependency update would be accepted in case of potential PR?
I see that prometheus is widely used and also there are some locked dependencies like:

// Keeping this same as Cortex to avoid dependency issues.
replace k8s.io/client-go =&gt; k8s.io/client-go v0.19.4

So it may cause some other issues for Loki?

**Comment by arempter** [comment]
the check I did above was for v2.2.1 release. Since this code is already part of main branch, I've just added PR to document it

**Comment by owen-d** [comment]
Thanks, going to close as it's included in our vendored updated + the docs

**Comment by StefanCenusa** [comment]
@owen-d @arempter  I think this issue refers to the [fluentd client](https://github.com/grafana/loki/blob/a9d85de4aa5290cf2f8b2dca5d08645bbd0dc66c/clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L116), not promtail. The fix referenced only covers promtail client. Thus, the issue is not finished.

**Comment by owen-d** [comment]
Oops!

**Comment by StefanCenusa** [comment]
not stale

**Comment by ecusnir** [comment]
Not stale

**Comment by ecusnir** [comment]
Not stale. It would be great to have a better method for authentication rather than basic auth or static bearer tokens when using the Fluent plugin 😄
