### ISSUE TITLE
Grafana Loki multi cluster setup 

### ISSUE THREAD

**Issue by venkatarajv** [grafana/loki#3150]
we have multiple cluster where we use Loki as logging service. now we are thinking of implement central logging service where we can see logs from all the cluster. straight forward solution is deploy Loki stack and start pushing logs from all remote cluster. but this will incur data transfer cost. we are thinking a more optimised solution like each cluster will have their own loki instance and central loki instance will connect to all the cluster. when ever they want to see logs user can login to central one and then can access logs. Any thoughts or suggestion on this?

**Comment by owen-d** [comment]
We have thought about this, but there is currently no federated loki option. Perhaps in the future, though :)

**Comment by venkatarajv** [comment]
Thank you for your response.

**Comment by justinmchase** [comment]
Prometheus exposes a /federate endpoint, its pulling logs instead of pushing so it can simply have other prometheus instances added to its scrape configs.

Here, it would be nice if you could configure a push target, or even all of the logs were published to a file in a way that a promtail sidecar like I have on my apps coudl then grab up all the data from one node and push it out to a node higher up in the hierarchy.

**Comment by justinmchase** [comment]
If this feature is not supported then how do you support horizontal scaling? How are databases configured to join their data?
