### ISSUE TITLE
filter fail

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#3177]
**Describe the bug**
logql：{filename="/var/log/system.log",job="varlogs"}|= "34"  
err：error while processing request: runtime error: slice bounds out of range [:177] with capacity 0

![image](https://user-images.githubusercontent.com/9583245/104710181-c04ee080-575a-11eb-8147-a1aa34d14d6f.png)

![image](https://user-images.githubusercontent.com/9583245/104710130-af05d400-575a-11eb-8f9b-248528095659.png)

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by yadutaf** [comment]
For the record, I hit a similar symptom on a custom build of v2.2.1 with golang 1.16 while official releases are based on 1.15. This was fixed after applying https://github.com/grafana/loki/commit/d6ecfd24313ecc9ad03e26875cb11394de7e988a which is on "main" but not yet in a release.

**Comment by k8xst08htbn78gcd** [comment]
Also encountered this. Occasionally, able to workaround issue by including "^" in a way to allow for matching from start of line.
For example, while matching some Webkit related messages in osx syslog,
- instead of this: `{job="varlogs"} |~ ".*origin = .*"`, (which inexplicably stopped working  after some restarts of loki/promtail/grafana stack)
- use this: `{job="varlogs"} |~ "^.*origin = .*"`.
I see a fix is submitted recently: awaiting its availability via homebrew!
