### ISSUE TITLE
Regular expression IN query

### ISSUE THREAD

**Issue by mnadeem** [grafana/loki#3328]
With reference to [this issue](https://github.com/grafana/loki/issues/3322)

I have got lots of job starting with lets say `oc-org-app-hsc`

````
oc-org-app-hsc-a1
oc-org-app-hsc-a2
oc-org-app-hsc-a2

some other apps
oc-org-app-pvc-a2
oc-org-app-pvc-a1
````

my intent with the following expression was, find `176975405` in all jobs starting with `oc-org-app-hsc-`

```
{job!="oc-org-app-hsc-*"}  |= "176975405"
```

Just now I have tried it is working like a charm.

![image](https://user-images.githubusercontent.com/476145/107675813-78ba6680-6cbe-11eb-92bb-66345a9f2113.png)

following is working as well

````
{job=~"oc-org-app-hsc-.+"}  |= "176975405"
````

If the following is not supposed to work then there is a problem, since it is working like a charm, **s there any bug**?

````
{job!="oc-org-app-hsc-*"}  |= "176975405"
````
**Note : I don't see any difference in result for both**

````
{job=~"oc-org-app-hsc-.+"}  |= "176975405"
````

and 

````
{job!="oc-org-app-hsc-*"}  |= "176975405"
````

**Comment by cyriltovena** [comment]
You're getting tricked, because your query return everything and so result are there. Loki basically go across all data when you do this
`{job!="oc-org-app-hsc-*"}  |= "176975405"` because nothing do not match `oc-org-app-hsc-*` it's not a regex if it doesn't have either `!~` or `=~`.

I believe the correct query is `{job!~"oc-org-app-hsc-.*"}  |= "176975405"` but it's bad you need an equality matcher.

**Comment by mnadeem** [comment]
FYI : This does not work

````
{job!~"oc-org-app-hsc-.*"} |= "176975405"
````
