### ISSUE TITLE
WAL introduces duplicates.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#3378]
**Describe the bug**

I was chasing for a bug and realized that the WAL when rolling out introduces duplicates entries next to each other in a chunk block.
I added a log line to prove it and every times I do a rollout I can see duplicates showing up. The push path protects from dupes thus why.

**Expected behavior**

No duplicates 🤷‍♂️ .

**Screenshots, Promtail config, or terminal output**

<insert duplicate screenshot>

/cc @owen-d

**Comment by owen-d** [comment]
Hm, I guess this could happen when replaying a checkpoint and then the segments. It's possible that by the time a series is checkpointed, it includes data which is also present in the segments that will be replayed as well. I suspect this will only happen for a single timestamp as previous pushes that are already present would 400 due to ordering errors. Thus I think it'd only be possible for the most recently written timestamp per stream. Is that in line with what you saw?

**Comment by cyriltovena** [comment]
Yes this was recent timestamp, next to each other. My log to find them was only logging exact line next to each other in a block.

**Comment by owen-d** [comment]
I think it's because we're not populating this field after checkpoints: https://github.com/grafana/loki/blob/master/pkg/ingester/stream.go#L172-L174
