### ISSUE TITLE
Promtail config for custom path of log folder

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#339]
I have logs in a specified path of a container other than var /log /containers .I would mount the log path to hostpayh say /home/mylog. Now I would use that path in promtail configuration 
Let me know if this works .also a sample of for the same would be helpful.thanks

**Comment by soum1234** [comment]
any update pls

**Comment by woodsaj** [comment]
What you are describing can be done.  But there are a number of factors you need to consider.
When running in k8s with the example scrape_configs provided, promtail gets the list of containers running on a node and starts collecting their logs. Promtail automatically adds labels to these logs, such as the POD name, container_name and any labels that exist on the pod.

For what you are describing, you would also need to make sure that you enrich the logs from `/home/mylog` with a similar set of labels.  There are a number of ways to do this, but my recommendation would be to use POD annotations that can pass information about the additional log paths to promtail.

The scrape_configs in promtail use the prometheus configuration libraries, so refer to the prometheus docs for more details on what can be done. https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

With that said, if you have containers that are writing logs to local files instead of to stdout or stderr, then using a promtail sidecar container is probably going to be a simpler approach. With this approach you can just use "emptyDir" volumes shared between the application and promtail containers instead of using hostPath volumes.

**Comment by soum1234** [comment]
Thanks a lot for the reply
i could infact send a custom path log file to loki 

Regards
sou

**Comment by kapendrasingh** [comment]
my situation is a bit different, i have a location inside pod "/var/log/app/log" or /var/www/html/vendor/logs . i want these logs to be read by promtail

i am getting other logs as std/out and I am running loki-stack with promtail as daemonset.

**Comment by kapendrasingh** [comment]
> i could infact send a custom path log file to lok

may i know hoe you did it

**Comment by kapendrasingh** [comment]
hi any update??

**Comment by cyriltovena** [comment]
You need to run promtail inside your container or as a sidecar if you want to scrape file inside the pod. Log file from kubernetes can be read by the default daemonset deployments because they are on the host.

**Comment by kapendrasingh** [comment]
same question but this time for Loki 2.0 and I have few log locations inside pods

1.  "/var/log/log/" 
2.  "/var/www/html/laravel.log" 

We want these logs to be read by promtail and realized we can do it by running promtail as a sidecar but its resource extensive solution 

We are  running Loki-stack with promtail as daemonset on k8s version 1.15

so, just looking for a solution which is not resource extensive and easy to deploy and manage. (LOKI 2.0)

**Comment by kapendrasingh** [comment]
i have tried to mount my log location to mount on the worker node-fs but I ain't able to scrape this on promtail. 
will this work? any promtail config to ship logs to loki?

**Comment by kapendrasingh** [comment]
any update ??

**Comment by zakkg3** [comment]
For those are looking to consume files and ship them to loki the getting started config shows that:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
 ```

https://grafana.com/docs/loki/latest/getting-started/get-logs-into-loki/

**Comment by saireddyb** [comment]
https://medium.com/linkbynet/getting-nodes-logs-with-promtail-daemonsets-4fb86c9fb8da

This article show how to get custom path file logs with promtail deamonset.

**Comment by popilmv** [comment]
Hello everybody. 

I am also interested in this opportunity. 
I found many examples of adding paths from **node to pod**. 
But is there an option to implement this:

There is a standard path from which logs are collected like **/var/log/pods/<name_of_pod>/<name_of_container>/0.log**. 
I have a container in which logs are written in **/app/logs/my.log**

How to see exactly the logs from **/app/logs/my.log** in Grafana?
