### ISSUE TITLE
SNMP Trap support

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#3399]
**Is your feature request related to a problem? Please describe.**
I need to collect SNMP traps and send them to hosted Loki (Grafana Cloud).

**Describe the solution you'd like**
I'd like to be able to send traps to Promtail, just like syslog

**Describe alternatives you've considered**
Right now I'm planning on using Telegraf, which has an SNMP trap input plugin. I'm waiting for the Loki output plugin to be merged (there is a pending PR).

**Additional context**
If there is no plan to support SNMP trap in Promtail it's not the end of the world, since it will be possible using Telegraf, however Promtail does support syslog, adding SNMP trap support would make it an "all-in-one" option for network device monitoring.

**Comment by xkilian** [comment]
snmptrap support is best handled by a mature third party: snmptrapd + snmptt + *syslog -> promtail. Or if you are satisfied by Telegraf. I personally do not see any value in complexifying promtail for this use-case. There is just too much involved in supporting this: SNMP v1/v2 traps/informs, snmpv3 encryption/hashing, decoding, compiling mibs, munging the format, etc.

FYI, looked at improving snmptt with Alex Burger so that it could be sent from snmptt directly to promtail. Sadly, there are no good perl syslog libraries for sending RFC5424+buffering+retry management. But, he will be introducing formatting in key=value format so that it can be logfmt compatible in Loki. So keep an eye on the next beta release of snmptt.

Telegraf is based on snmptranslate which is a good intermediate/simplified handling for traps. Does not permit categorisation of severity or handling of variables, but is a nice compromise. As you said, it needs loki/splunk/etc output to be useful as snmptraps are events, not metrics.

I have looked at NxLog commercial version, promising but it does not handle correctly additional variables and they are not decoded from the mibs. It also causes label cardinality explosions. Not ready for primetime...
