### ISSUE TITLE
logfmt Parser Splitting parameter

### ISSUE THREAD

**Issue by jain-harshil** [grafana/loki#3558]
**Is your feature request related to a problem? Please describe.**
Currently, logfmt supports finding key value pairs i.e. key=value pair. Is there any option where we can specify a custom delimiter like ': ' [colon followed by space]. So that key: value pair is also extracted as a key-value pair.

@jeschkies I request you to please help me with this...

Thanks.

**Comment by jeschkies** [comment]
Thanks for posting your question here. If I read [decode.go](https://github.com/grafana/loki/blob/master/pkg/logql/log/logfmt/decode.go#L59) correctly there is no support for another separator char. However, I see value in adding an option for an alternative separator. The format could be `logfmt sep=":"`. However, the [logfmt spec](https://brandur.org/logfmt) implies `=` as a separator.

@cyriltovena, what do you think?

**Comment by cyriltovena** [comment]
I'm not opposed to the idea. but yeah that's not logfmt anymore.

@jain-harshil what's that format name you're using ? how did it get generated like that ?

**Comment by ghseb** [comment]
Hello,
I would like to reopen a discussion on exactly this topic. We got logs to analyse that use the `key: value`-pattern and using some `logfmt`-like utility would simplify things a lot in comparison to usage of regular expressions.

Theoretically we could align the logs to the logfmt-format, but since we utilize a lot of third party code, that we have no control of, this would only partially solve the issue.

In general I think that support for other formats would allow to use grafana/loki in a lot of additional use-cases.

I see the following possibilities:
- Continue to use `regexp`
- Convert logs to the logfmt-format using promtail and regular expressions
- Try to push upstream https://github.com/go-logfmt/logfmt to support additional key-value separators
- Make an additional custom change in loki's logfmt implementation
- Add an additional log-line interpreter that supports the `key: value`-pattern

What do you think about the topic?

I'd appreciate some guidance or thoughts on the described topic.

Thanks!

**Comment by jain-harshil** [comment]
I had modified logfmt to support key:value and key=value (with spaces around operators, i.e. key: value, key = value and so on). But logfmt is known to just have key=value. So not sure if it should still be called logfmt.

**Comment by jeschkies** [comment]
> We got logs to analyse that use the key: value-pattern

@ghseb, is there a special reason why this is the case? Is this a known format?

**Comment by ghseb** [comment]
@jeschkies No, we use the pattern partly for historical reasons and because third party libraries we use, perform debug printout that way.

I probably should say that we are not analysing logs from desktop/server applications, but from embedded devices.
