### ISSUE TITLE
update docs for azure storage

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#3774]
This issue was closed, but docs are still missing: https://github.com/grafana/loki/issues/2907

**Comment by dannykopping** [comment]
Feel free to comment on the original issue; I'm going to close this one in favour of that one.

**Comment by Morriz** [comment]
what do you mean you favor a closed issue that has no resolution?

**Comment by Morriz** [comment]
Not nice to close issues like that.

**Comment by dannykopping** [comment]
I apologise @Morriz - I neglected to reopen the issue; in any case, it was only closed due to staleness, not because we don't want to do it.

I have reopened it now.

For future reference, you can comment on closed issues and request reopening if the issue goes stale - that is preferable to opening a new issue.
