### ISSUE TITLE
Timestamp Fraction of second precision in custom format with comma separator in date

### ISSUE THREAD

**Issue by fraktury** [grafana/loki#3961]
Hello,
I want to extract my date with the stage timestamp but my date contains a 3-digit precession (milliseconds) prefixed with a comma and not with a point as required by the custom format
Date example: 
2021-07-07 17:40:45,052

The stage timestamp documentation indicate that i must use ".999" in my custom format but it is a comma that is used in my date. 
I tried several format but none works. 
format: "2006-01-02 15:04:05,999"
format: "2006-01-02 15:04:05,.999"
format: "2006-01-02 15:04:05.999"

To test, if I change the comma to a "." in a line, it is parsed correctly with this custom format: "2006-01-02 15:04:05.999"

As the "." is imposed, how can I do with my comma?
Having multiple lines in the same second, it is important that this information is taken. Regarding the format of the date in my log files, it is directly managed by the ASP engine, I have no control over it

Thank you for your help and any workaround you could offer me.

**Comment by hterik** [comment]
This is a very old bug in the go time package that was recently fixed in 1.17: 
See https://go-review.googlesource.com/c/go/+/345438/ and  https://github.com/golang/go/issues/6189 
Latest version of Promtail uses go1.16.2 
```
promtail, version 2.4.2 (branch: HEAD, revision: 525040a32)
  build user:       root@5d9e7a4c92e6
  build date:       2022-01-12T16:48:53Z
  go version:       go1.16.2
  platform:         linux/amd64
```
Only workaround i'm aware of is manually format the string to separate the comma between second and fractions. Replacing it with some other dummy separator.

Can this be reopened?
