### ISSUE TITLE
loki_ingester_memory_chunks metric doesn't account for WAL replay

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#4004]
Noticed this after helping a user in public slack and seeing this as a negative value.

**Comment by taisho6339** [comment]
I reproduced "negative value" like this
<img width="1916" alt="negative_value" src="https://user-images.githubusercontent.com/1638833/132847296-81badce9-41c1-42d0-b422-9e5fb1db752b.png">


I've fixed in the PR
<img width="961" alt="after" src="https://user-images.githubusercontent.com/1638833/132847353-4e5a4ee5-ccc8-4dfc-bbfb-eef86507241f.png">

I'd be happy if you could confirm it
