### ISSUE TITLE
AWS Cloudwatch logs scrape config

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#4129]
Now that Loki can accept out of order writes, I think we should implement an AWS Cloudwatch Logs scrape config, similar to `gcplog`

ref: https://github.com/grafana/loki/issues/1544

**Comment by ruanbekker** [comment]
This will be awesome! In my personal opinion, viewing cloudwatch logs has always been a bit of a mission, not to mention grepping for things.

Being able to use Loki to view CloudWatch logs will be a massive win!

**Comment by zswanson** [comment]
Take my money

**Comment by zswanson** [comment]
@owen-d FYI cloudwatch has hard quotas on GetLogEvents API call
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

> GetLogEvents | 10 requests per second per account per Region. This quota can't be changed.We recommend subscriptions if you are continuously processing new data

**Comment by james-callahan** [comment]
> Info on cloudwatchlog subscriptions - https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Subscriptions.html

Looks like the only reasonable option there is a lambda. At which point, with loki accepting out-of-order writes, isn't that just the already-existing lambda-promtail?

**Comment by owen-d** [comment]
Yeah @james-callahan, you're correct. I'm hoping we can make it a little easier with some additional tooling that @cstyan is looking into :hugs:

**Comment by sachin064** [comment]
Any alternative for this plugin in AWS cloud

**Comment by AndreZiviani** [comment]
keepalive

**Comment by IppX** [comment]
Lambda promtail already solves the problem for the simple use case of forwarding a few log groups to Loki.

At scale though, it could be interesting, instead of a Cloudwatch scrape config, to add a Firehose server endpoint/option to promtail. That way we could send logs cross account and cross region (via subscriptions) to promtail that would then forward it to Loki.

That's also what other vendor solutions like Datadog,Honeycomb,Splunk have implemented, see the list [here](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html).

Is there anything already on the roadmap for such a feature?

**Comment by jeschkies** [comment]
> Firehose server endpoint/option to promtail

I like the idea. I wonder if it should be part of Promtail though. So far Promtail was only pull/scraping logs.

**Comment by IppX** [comment]
> So far Promtail was only pull/scraping logs.

I was thinking by adding an option like: `[type: "promtail" (default) | "firehose"]` or `[api: "promtail" (default) | "firehose"]`; in [the server config](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#server) which is more a way to push log from my understanding.
Could this work or is it stretching the original design too far?

An alternative could also be to introduce a concept of "input" similar to fluentbit.
