### ISSUE TITLE
Promtail Sending Compressed logs to loki?

### ISSUE THREAD

**Issue by zainaliVeeve2695** [grafana/loki#4144]
### Questions

- Does promtail send compressed logs to loki?
- if answer to first question is yes then, What is the default compression?
- if answer to first question is yes then, How can we change the compression type?
- if answer to first is no then, what can be the alternative solution to push logs in compressed form?

### Problem
- I am pushing the logs to loki server using promtail but log size is too big and its taking a lot of network bandwidth.

**Comment by ai-denlim** [comment]
I would like to know as well 👍🏼

**Comment by ronensc** [comment]
Looking at Promtail's source code, it seems that it uses Google's snappy-compression and currently, there is no way to configure it otherwise.

code references:

1.
https://github.com/grafana/loki/blob/79d53317dd34d32140fd7067fe68ad1c1c0ab26a/clients/pkg/promtail/client/client.go#L293-L294

2.
https://github.com/grafana/loki/blob/79d53317dd34d32140fd7067fe68ad1c1c0ab26a/clients/pkg/promtail/client/batch.go#L93-L95

**Comment by cyriltovena** [comment]
Correct promtail uses snappy, the API support also json/gzip but that's not used in Promtail.
