### ISSUE TITLE
[rate limiter] distributor: rate limiter do not work well，Too much CPU waste

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#4148]
ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20

![image](https://user-images.githubusercontent.com/9583245/129130027-e478961c-02f7-4647-ac42-f8b2f9ca2b19.png)
![image](https://user-images.githubusercontent.com/9583245/129130141-d84c0af1-ea42-4dcf-894b-e80ce816f0fd.png)
![image](https://user-images.githubusercontent.com/9583245/129130218-93eef6bf-f610-4674-a14e-2d25b971d0c1.png)

**Comment by cyriltovena** [comment]
I think what you're saying is that rate limiting is working but still does consume a lot of CPU.

Something we can try to improve but most of the work is about unpacking lines to calculate the non compressed size since the rate limit is about uncompressed data. Seems like you're sending JSON may be proto would do better ?

**Comment by liguozhong** [comment]
Yes, can loki add a rate limit mechanism based on the number of requests?
we need a rate limit mechanism with low CPU consumption

**Comment by owen-d** [comment]
I also support Cyril's suggestion to move to [snappy-encoded protobufs](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push). Rate limiting based on bytes as opposed to requests is important as not all requests may be the same size.
