### ISSUE TITLE
Positions stored in host path volume

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/loki#416]
**Is your feature request related to a problem? Please describe.**
Currently `positions.yaml` is stored in a hostPath volume at `/run/promtail/positions.yaml` (using Helm). Using hostPath to store state is brittle, insecure and not scalable:

- Brittle in case the file is deleted accidentally on the host
- Insecure in the sense that hostPath volumes do not respect `fsGroup`, so you have to run promtail as root
- Not scalable when a use case for running multiple promtails per node comes up in the future that's difficult/error-prone with host path

**Describe the solution you'd like**
Since a PVC is not feasible with daemonsets, I think there are 2 approaches with various trade-offs:

* Use emptyDir per pod
   * Pros: Simple, data persistent between restarts, treats positions as temp/best effort data
   * Cons: Data deleted if pod deleted, duplicate data sent to Loki (does Loki ignore?), performance when missing?
* Move state to Loki, retrieve positions/last timestamp on startup
   * Pros: Loki becomes stateless, no volumes necessary
   * Cons: Complexity, Loki might be down

**Describe alternatives you've considered**
See above.

**Additional context**
Trying to reduce promtail's runtime privileges.

**Comment by steven-sheehy** [comment]
I like option 2, and it's the option I took in my PR #413. Loki should ignore duplicates (if not already) regardless of which option is chosen. So might as well make Loki and Promtail resilient to missing positions and treat the positions as temporary data that can be recalculated if needed.

**Comment by kfox1111** [comment]
There is already additional state outside this position that needs to be maintained. The Logs themselves. So this part of the system is kind of inherently stateful. putting it close to the logs with a hostPath does not feel too weird in this case. /var/log/positions.yaml on the host seems bad. /var/log/promtail/positions.yaml would be much better as the directory can be imported and permissions changed.

One PVC per node seems extremely wasteful/slow. There is no native support in Kubernetes for that either. One PVC for all nodes feels like it would scale poorly and provides a pretty bad single point of failure in most instances.

emptydir is not safe to use when upgrading the software, which should happen as frequently as necessary for proper operations. We don't want to feel obligated not to apply fixes cause it might spew too much data. It might be ok if loki had some form of duplicate suppression. That sounds hard though.

Storing state to loki is an interesting suggestion. I do wonder how difficult that would be to scale though.

Without a non trivial amount of effort from loki, I think of the 4 options, leaving it as hostPath is the least bad.

**Comment by steven-sheehy** [comment]
> There is already additional state outside this position that needs to be maintained. The Logs themselves.

Logs are not application state, they are read only files that are not promtail's responsibility to maintain.

> One PVC per node seems extremely wasteful/slow. There is no native support in Kubernetes for that either.

Not true about no support, there's nothing stopping a DaemonSet from declaring a persistentVolumeClaim in its list of volumes.

> leaving it as hostPath is the least bad

If a use case for running multiple promtails per node come up in the future that's not possible with host path.

**Comment by kfox1111** [comment]
> Logs are not application state, they are read only files that are not promtail's responsibility to maintain.

This is true. but logs are state on the machine must already be maintained by operators. I'm not addressing by which software is responsible. So keeping an additional piece of state on the host tied to the lifecycle of the host/logs is not a big load for operators. Putting the state there doesn't increase the complexity an operator needs to deal with. Thats all I'm saying.

> > One PVC per node seems extremely wasteful/slow. There is no native support in Kubernetes for that either.
> 
> Not true about no support, there's nothing stopping a DaemonSet from declaring a persistentVolumeClaim in its list of volumes. There would be one pvc for each pod created, not one for all pods.

That is not how pvc's work. The only thing that works like that is a StatefulSet with its volumeClaimTemplates property (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#statefulsetspec-v1-apps). That creates a PVC per pod. a PVC has a 1:1 relationship with persistent volumes.

A daemonset can only reference an existing PVC which will be shared between all pods in the daemonset.

> > leaving it as hostPath is the least bad
> 
> If a use case for running multiple promtails per node come up in the future that's not possible with host path.

Sure it is. use a different host path. :) helm makes that pretty easy.

I do get what your saying there. it would be nice if it didn't have to care. I think per tenant log shipping should really be a feature k8s would support. I don't think the hostpath workaround for now is a big enough problem though as CRI would need a big rewrite with respect to logging to get to the point of needing it. Much longer term issue.

Longer term too, things like the ephemeral csi driver support that I and others have been working on (alpha in 1.14) could be used as part of the solution. I've always envisioned an ephemeral driver like emptydir thats lifecycle was more tied to a namespace then a pod, so that namespaces could store a bit of storage longer term. This use case might fit that kind of storage driver.

**Comment by steven-sheehy** [comment]
Ah, you're right about PVCs being shared among daemonsets, so I removed that as an option.

Another problem with host path is that it does not respect `fsGroup`, so running as non-root is not possible even if your volumes have the appropriate permissions to support it.
