### ISSUE TITLE
Logstash - version mismatch on plugin installation

### ISSUE THREAD

**Issue by christineywang** [grafana/loki#4179]
**Describe the bug**
For the Logstash Loki plugin, users get a version mismatch on plugin installation because a dependency was updated recently.

`logstash-codec-plain`

We may want to use a `~>` for the dependency.

**Comment by OranShuster** [comment]
Happening to me also on logstash `7.15.0`/`7.15.1`/`7.15.2`

it seems the plugin does install successfully on logstash `7.14.1`, there should be a section in the docs about version compatibility

**Comment by npampaloni** [comment]
I'm experiencing the same issue on 7.15.2.

**Comment by softwareengel** [comment]
Happening to me also on logstash 7.15.2

**Comment by vincenthodicq** [comment]
Thanks @OranShuster for the info on `7.14.1`. Was experiencing same issue on latest version.

**Comment by BenCoughlan15** [comment]
Happening to me also on logstash 7.16.1

**Comment by martensson** [comment]
Worth to mention that 7.16.1 is required to mitigate log4shell as well. So downgrading is not an option for us at least.

**Comment by cyriltovena** [comment]
What's the suggested fix I'm not a Java/Jruby expert ? Do we need to update something?

**Comment by martensson** [comment]
A believe either wait or maybe use something like Vector to replace Logstash or in between (Logstash->Vector->Loki). But it adds complexity, so I really hope a new version is around the corner.

**Comment by slim-bean** [comment]
Hey all! sorry we didn't catch this sooner.

Would love to update this for everyone, does someone here know exactly what we need to do? (If not we'll dig into it but would be great to save some work if we can)

Thanks!

**Comment by OranShuster** [comment]
> Hey all!
> 
> Would love to update this for everyone, does someone here know exactly what we need to do? (If not we'll dig into it but would be great to save some work if we can)
> 
> Thanks!

i'm not a ruby dev by any means but it looks to me like a transitive dependency mismatch 
this also matches what the OP, christineywang , said
this might be solveable by simply updating the offending dep

**Comment by christineywang** [comment]
This is a dependency issue. I've had a user fix this by changing the gemspec. He created a new version and removed this line: `s.add_runtime_dependency "logstash-codec-plain", "3.0.6"` and added this `s.add_runtime_dependency 'logstash-codec-plain'`.

**Comment by cyriltovena** [comment]
Pushed a new gem https://rubygems.org/gems/logstash-output-loki/versions/1.0.4 it should fixes the issue otherwise let me know we might need to change the depencies.

**Comment by maxdialpad** [comment]
Hey Cyril,

Thanks for updating this. We've been keeping a local gem that we installed from manually.

For reference, here's my diff I used to fix this on our end.
Warning: I am not a Ruby dev!
```
diff --git a/clients/cmd/logstash/logstash-output-loki.gemspec b/clients/cmd/logstash/logstash-output-loki.gemspec
index 0b9bbe77a..5441ce9d9 100644
--- a/clients/cmd/logstash/logstash-output-loki.gemspec
+++ b/clients/cmd/logstash/logstash-output-loki.gemspec
@@ -1,6 +1,6 @@
 Gem::Specification.new do |s|
   s.name    = 'logstash-output-loki'
-  s.version = '1.0.3'
+  s.version = '1.0.4'
   s.authors = ['Aditya C S','Cyril Tovena']
   s.email   = ['aditya.gnu@gmail.com','cyril.tovena@grafana.com']

@@ -21,6 +21,6 @@ Gem::Specification.new do |s|
   # Gem dependencies
   #
   s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60", "<= 2.99"
-  s.add_runtime_dependency "logstash-codec-plain", "3.0.6"
+  s.add_runtime_dependency 'logstash-codec-plain'
   s.add_development_dependency 'logstash-devutils', "2.0.2"
 end
```

I just tried installing the latest `1.0.4` and I can confirm it works for me. Thanks for uploading the new gem.
Unless there's opposition, I think this issue can be closed.

**Comment by OranShuster** [comment]
@cyriltovena A couple of suggestions to make this plugin more friendly to new users
this is with regards to the loki documentation here https://grafana.com/docs/loki/latest/clients/logstash/
1. Update the code snippet with the latest version (1.1.0)
2. Add a link to the [rubygems page ](https://rubygems.org/gems/logstash-output-loki/versions/) so users can find newer versions of the plugins if the docs are not updated
3. Maybe a note about that the plugin is installed from a public ruby repository so its more clear where things are coming from

With regards to the images in dockerhub
1. there seems to be 2 types of images, `main` and `k84`, yet the docs don't say anything about the differences between them
2. the tags are probably the SHA when the image was built? in any case, users have no idea what logstash version is used or what plugin version is used. Looking at the image layers doesn't reveal much
3.A link to the [repository plugin folder](https://github.com/grafana/loki/tree/main/clients/cmd/logstash). Since there is no official changelog in rubygems or in dockerhub, users can see from the commits what changes are in each image
