### ISSUE TITLE
Promtail Service discovery global labels option

### ISSUE THREAD

**Issue by Karabiy** [grafana/loki#4317]
In case if I have a setup with a service discovery ( AWS ) 
like 
scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 30h 
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: ec2-logs
    ec2_sd_configs:
      - region: us-east-2
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        action: replace
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
        action: replace
      - source_labels: [__meta_ec2_availability_zone]
        target_label: zone
        action: replace
      - action: replace
        regex: ".*"
        replacement: /var/log/**.log
        target_label: __path__
      - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*)"
        target_label: __host__

I am a kind of frustrated, as I want for all my jobs to have ec2 related labels, and this doesn't feel to be possible at all. 
The way I can see it, have an additional labels as hierarchy option, and have an option to have in there the relabling being handled 
something like:
labels: 
   ec2_sd_configs: ...
   relabeled_configs: ... 
So that there will be no need for duplication  

It would be much more user-friendly.
Related issue: #2707

**Comment by kasper-leFevre** [comment]
still ni updates on this?

**Comment by cstyan** [comment]
Hello, thanks for your feature request.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.
