### ISSUE TITLE
gRPC too_many_pings errors in the default grafana/loki:k64-12253ec docker container

### ISSUE THREAD

**Issue by Edvecs** [grafana/loki#4375]
Before upgrading loki I have pulled the latest loki release to test it on my localhost:
`$ docker run grafana/loki:k64-12253ec`

and I see the following errors in the logs:

`level=error ts=2021-09-24T06:31:21.506378051Z caller=frontend_processor.go:70 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings"
`

I am wondering if this is known and if you have a fix for it?

**Comment by cyriltovena** [comment]
This is because some subqueries are getting cancelled by the frontend since it has enough result to fulfil the original request.

Unfortunately GRPC client side can't make the distinction of that cancellation see the [doc](https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-termination) : 

> In gRPC, both the client and server make independent and local determinations of the success of the call, and their conclusions may not match. This means that, for example, you could have an RPC that finishes successfully on the server side (“I have sent all my responses!“) but fails on the client side (“The responses arrived after my deadline!“). It’s also possible for a server to decide to complete before a client has sent all its requests.

The only option I see is to downgrade EOF error to info in cortex code to https://github.com/grafana/loki/blob/main/vendor/github.com/cortexproject/cortex/pkg/querier/worker/frontend_processor.go#L70.

If anyone wants to take a stab feel free !

**Comment by dannykopping** [comment]
We should adjust our default settings based on the changes made in this PR:
https://github.com/grafana/loki/pull/4182/files

@Edvecs can you try configuring these settings and seeing if that resolves your issue pls?

**Comment by owen-d** [comment]
@Edvecs try adding these configs to your GRPC server:
https://github.com/grafana/loki/pull/4182/files
