### ISSUE TITLE
Promtail may fail to scrape pods if the only label that changes is the filename

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#4581]
**Describe the bug**

The code which decides if a file target is a duplicate to an existing target compares all the labels __except__ the filename label (which at this point in the code is `__path__` pulled from the scrape_config).

This means if the *only* label that changes is the filename label when a pod is restarted, it will fail to be scraped because the code will consider it a duplicate of an existing target and ignore it.

A workaround would be to add any label which changes when the pod is restarted. 

Add something like this to each job in your scrape config
```
- action: replace
   source_labels:
     - __meta_kubernetes_pod_uid
   target_label: pod_uid
```

Reminder, this is a workaround until a proper fix is put in place in Promtail.

Note: 

This is likely largely not seen previously because a lot of the example scrape configs we've provided have always included a section which maps all the pod labels to Loki labels, which includes things like `pod_template_hash` and `controller_revision_hash` that will always change when pods are restarted.  

Our more recent guidance suggests not mapping all pod labels to Loki as they often have little value for querying and result in wasted index space, as a result we have since discovered this issue on more recently provided scrape configs such as provided with the Grafana Agent.

**Comment by rsteneteg** [comment]
@rfratto AFAIK when it comes to simple datatypes like a string, the only issue with multiple threads reading/writing to it, is that there is no guarantee on which threads reads or writes first, so the value the reading thread gets back depends on if the writing thread updated the value before or after the reading thread.
Depending on your use case it may or may not matter which order the threads runs, in this case for Promtail if the new value for path is written after the read, the new value will just be read on the next sync interval. And the reason golang complains about it when using the race detector is that there could be uses cases when the reading thread might not do another read, or if the value it reads must be the new one on the first attempt.

**Comment by rfratto** [comment]
Thanks for explaining.

> there is no guarantee on which threads reads or writes first, so the value the reading thread gets back depends on if the writing thread updated the value before or after the reading thread.

This doesn't sound quite right. If this were true, it implies that Go only allows access to a section of memory one thread at a time, and there would be no point in having mutexes. Am I understanding correctly? Concurrent reads and writes _are_ undefined behavior. 

It is possible for the reading goroutine to get a partial read of the updated memory of the struct field. This read would be a corrupted string, which would lead to at least two scenarios:

* Best case scenario: you get back a valid struct that still points to an allocated string on the heap. The FileTarget tries to treat this as a file path, probably fails, and waits for the next updat. 
* Worst case scenario: you get back an invalid struct that is not pointing to an allocated space on the heap. This would lead to a panic. 
 
I'm only strongly considering the issues with reading here, which I believe we can probably agree is more likely to be a real problem. I haven't been able to disprove that a write can't be corrupted by a concurrent read. We can't know for sure since it's undefined behavior, but the possibility of a corrupted write would surprise me a little. 

All that said: even if it was completely impossible for the data race to corrupt a read and lead to a panic, I still think we should change the code, just in case. There's no guarantee that FileTarget won't change in the future in a way where the data race causes a more serious and common issue. Having to keep that in mind is a bit of cognitive overhead that I think Promtail contributors shouldn't have to worry about.

**Comment by rsteneteg** [comment]
@rfratto Ah yeah your right, I'll try out to have a new filetarget be created instead

**Comment by rsteneteg** [comment]
@rfratto I created a new PR with a more simple fix that don't require a mutex by instead using the path in the labels key to identify filetargets, so when the path changes it is treated as a new filetarget as you suggested.

@slim-bean I don't think we can can made this fix any simpler than this :)

**Comment by slim-bean** [comment]
Thanks @rsteneteg !!
