### ISSUE TITLE
I did not find an interface that directly modified the "promtail-config.yaml" configuration information

### ISSUE THREAD

**Issue by lishensheng** [grafana/loki#4735]
I did not find an interface that directly modified the "promtail-config.yaml" configuration information

**Comment by dannykopping** [comment]
Please provide us with more details @lishensheng - this is not enough for us to assist

**Comment by lishensheng** [comment]
Can I add a configuration for "protail-config.yaml" using code.
Second, how to find files from two different servers and push them to the same "Loki".




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "grafana/loki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [grafana/loki] I did not find an interface that directly modified the "promtail-config.yaml" configuration information (Issue #4735)





 
Please provide us with more details @lishensheng - this is not enough for us to assist
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dannykopping** [comment]
We try to keep GitHub issues strictly for bug reports and feature requests.

This sounds like a question rather than an issue with Loki, so let's move the discussion to one of these channels:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.
