### ISSUE TITLE
AGPL-licensed Loki is incompatible with MPL-licensed Hashicrop code used in Loki

### ISSUE THREAD

**Issue by tonychoe** [grafana/loki#4890]
**Describe the bug**

There may be a license incompatibility between Loki’s AGPL license and the MPL licensed Hashicorp code used in Loki. In other words, **Loki may be violating the Hashicorp licenses.**

Hashicorp MPL licenses contain the Exhibit B - “Incompatible With Secondary Licenses” Notice. See Q14 in the [MPL FAQ 1](https://www.mozilla.org/en-US/MPL/2.0/FAQ/). 
Also see [Exhibit B](https://github.com/hashicorp/memberlist/blob/923f1b205dd4653f2ea35e1c9531088e52053aa0/LICENSE#L349-L354) and [Second License](https://github.com/hashicorp/memberlist/blob/923f1b205dd4653f2ea35e1c9531088e52053aa0/LICENSE#L72-L76_) in one of Hashicorp’s component. It clearly mentions it is incompatible with AGPL.

[List of MPL licensed code in Loki](https://github.com/grafana/loki/tree/main/vendor/github.com/hashicorp)
- github.com/hashicorp/consul/api 
- github.com/hashicorp/errwrap 
- github.com/hashicorp/go-cleanhttp
-  github.com/hashicorp/go-immutable-radix 
- github.com/hashicorp/go-multierror 
- github.com/hashicorp/go-rootcerts 
- github.com/hashicorp/go-sockaddr 
- github.com/hashicorp/go-uuid 
- github.com/hashicorp/golang-lru 
- github.com/hashicorp/golang-lru/simplelru 
- github.com/hashicorp/memberlist
-  github.com/hashicorp/serf/coordinate

**To Reproduce**
n/a

**Expected behavior**
The license incompatibility is remediated or explained why it is not an issue.

**Environment:**
n/a

**Screenshots, Promtail config, or terminal output**
n/a

**Comment by tonychoe** [comment]
@slim-bean can you please review?

**Comment by RichiH** [comment]
Thank you for your issue. As none of us are lawyers ourselves, we have reached out to our legal department for guidance.

**Comment by RichiH** [comment]
This is what we got from legal. As far as I understand, we can close this issue.

-----

Dear tonychoe, 

Thank you for your github issue (https://github.com/grafana/loki/issues/4890). We do not agree with your interpretation that there is any license incompatibility issue between HashiCorp libraries licensed under the Mozilla Public Licence (MPL) v2.0 and Grafana’s Loki project licensed under the Affero General Public License (AGPL) v3.0. AGPL is otherwise known as a “secondary license” within the meaning of that defined term in the MPL 2.0. We would like to clarify why we believe this for you and the community. 

The MPL license by its very terms is not compatible with secondary licenses but for the addition of section 3.3. With this provision included in the agreement, secondary licenses are compatible by fiat. Only where section 3.3 is invalidated does non-compatibility exist.  

For section 3.3 to be invalidated, the contributor must “opt-out” of the compatibility with secondary licenses by applying the example notice in exhibit B of the license in connection with the contribution. Simply pasting the text of the license is not enough to opt out.   

The license states as follows: 

1.5. “Incompatible With Secondary Licenses”
means

that the initial Contributor has attached the notice described in Exhibit B to the Covered Software (emphasis added); 

Covered software is defined as follows: 

1.4. “Covered Software”
means Source Code Form to which the initial Contributor has attached the notice in Exhibit A, the Executable Form of such Source Code Form, and Modifications of such Source Code Form, in each case including portions thereof.

The “Covered Software” is both the source and object code form and the Exhibit B sample notice must be affixed to both (along with any modified versions, if applicable).  

In speaking with outside advisors, including one or more of which were on the drafting committee of MPL, they confirmed that in order to invalidate the MPL’s compatibility with secondary licenses, the contributor must do more than simply attach a copy of the license agreement. They have to further affix the notice (which again is only referenced as an example in Exhibit B of the license) to the Covered Software. This is typically done in a readme file or as an annotation to the license - explicitly stating the contributor’s intentions to opt out of compatibility granted by section 3.3.  

We do not see anywhere within the applicable repos where HashiCorp has opted out of compatibility with secondary licenses - as such we do not see that there is any issue to resolve. If you believe such opting out has occurred, please point us to the documentation so that we can further review this. Otherwise, we will consider this issue closed.

Regards, 

Grafana Labs
