### ISSUE TITLE
Loki should not send "request was cancelled by the client" as an http response

### ISSUE THREAD

**Issue by bboreham** [grafana/loki#4991]
It is impossible for this to work if true - the way you cancel an http request is to close the socket, so if that has happened then the server cannot write the response.

But we do see such responses:
![image](https://user-images.githubusercontent.com/8125524/147099613-2bd5ad68-a98b-40da-bf09-ee2e520f4d86.png)

Such reports can come from here: https://github.com/grafana/loki/blob/e573a4d1a2d6f6ba627773cd8a24eacdd5a1b73e/pkg/util/server/error.go#L60

One improvement is to go to all the places where it is called, like https://github.com/grafana/loki/blob/e573a4d1a2d6f6ba627773cd8a24eacdd5a1b73e/pkg/lokifrontend/frontend/transport/handler.go#L125
and check if `r.Context()` has errored - if so then we should bail out and not write anything.
If not, we know the client did not cancel; some internal condition caused this, so we can return a 500 or similar.

It appears this code was added in #4593 in response to #4502.

**Comment by cyriltovena** [comment]
499 is mostly for us to have a status code for SLO reason.

I think the problem is this 

https://github.com/grafana/loki/blob/e573a4d1a2d6f6ba627773cd8a24eacdd5a1b73e/pkg/util/errors.go#L127

When we rollout this gets turned into 499, the frontend thinks it's a cancel and return cancel. It should 500 and the frontend will retry.

**Comment by vlad-diachenko** [comment]
The root cause of the issue is that the connection to the ingester is canceled here https://github.com/grafana/dskit/blob/main/ring/client/pool.go#L130 because the health check of GRPC connection is failed and when another goroutine that serves the request from the user tries to close the connection, it leads to the error.

**Comment by bboreham** [comment]
Sorry, that may be the root cause of why you see a cancellation, but the error I described is in the logic of how errors are reported, not how they are caused.

**Comment by vlad-diachenko** [comment]
you are completely right, and I will fix the logic of how the error is reported, but I had to understand why the issue happens... And now I see that we can also fix the root cause of the issue by adding retry mechanism to health-check or something like this...

**Comment by bboreham** [comment]
Good find!  Suggest filing that as another issue (in DSKit?).

**Comment by vlad-diachenko** [comment]
> Good find! Suggest filing that as another issue (in DSKit?

yes, I will report an issue in dskit. thanks.
