### ISSUE TITLE
promtail_read_bytes_total metric cannot be found

### ISSUE THREAD

**Issue by 83320843** [grafana/loki#5009]
I have a set of loki environments ，Loglogs are all extracted from the physical environment，and loki client and loki server built the directory separately，Prometheus was installed，Monitoring indicators can be seen,however, something similar to promtail_read_bytes_total cannot be found。Please help me, thank you
![image](https://user-images.githubusercontent.com/3615187/147546546-1df9962b-62c2-411c-b3c6-3b14717fbf15.png)

**Comment by dannykopping** [comment]
@83320843 it appears you are looking at Loki's metrics endpoint (I'm guessing, since your URL is xxx:3100 where 3100 is Loki's port).

You should be retrieving the metrics from the promtail instance running on the port specified in the `server` block:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#server under `http_listen_port`
