### ISSUE TITLE
having a built-in conf.d-style out of the box (container)

### ISSUE THREAD

**Issue by lastsky** [grafana/loki#507]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when config file doesn't support `conf.d` or `directory.d` style (example: https://github.com/axkibe/lsyncd/issues/441) and i need to code some 💩for automate deploy for 200+ servers

**Describe the solution you'd like**
I want prometheus but for logs

/opt/promtail/promtail.conf:

~~~YAML
<...>
scrape_configs:
  - job_name: stage
    entry_parser: raw
    env: stage
    file_sd_configs:
        - files:
            - '/opt/promtail/conf.d/stage/*.yml'

  - job_name: prod
    entry_parser: raw
    env: prod
    file_sd_configs:
        - files:
            - '/opt/promtail/conf.d/prod/*.yml'
~~~

/opt/promtail/conf.d/stage/db1.example.org.yml:

~~~YAML
  - targets:
      - localhost
    labels:
      service: database
      job: postgres
      server: db1
      __path__: /var/log/remote/stage/db1.example.org.log
~~~

/opt/promtail/conf.d/stage/db2.example.org.yml:

~~~YAML
  - targets:
      - localhost
    labels:
      service: database
      job: postgres
      server: db2
      __path__: /var/log/remote/stage/db2.example.org.log
~~~

/opt/promtail/conf.d/prod/web1.example.org.yml:

~~~YAML
  - targets:
      - localhost
    labels:
      service: frontend
      job: nginx
      server: web1
      __path__: /var/log/remote/prod/web1.example.org.log
~~~

/opt/promtail/conf.d/prod/web2.example.org.yml:

~~~YAML
  - targets:
      - localhost
    labels:
      service: frontend
      job: nginx
      server: web2
      __path__: /var/log/remote/prod/web2.example.org.log
~~~

**Describe alternatives you've considered**
- run multiple loki/promtail services with separate config one per env 💩
- run multiple loki/promtail servers one per env 💩

**Comment by lasczki-da** [comment]
any updates?

**Comment by cyriltovena** [comment]
Definitely interesting but we haven’t got the time to get started on this

**Comment by bnewbold** [comment]
A related use-case is configuring multiple services on the same host, independently. That is, deploy `promtail` with generic configuration, and then have each service/application install it's own promtail configuration file specific to that service.

For example, if installing `haproxy` on a host (using ansible, puppet, whatever), that install process would create an `/etc/promtail/conf.d/haproxy.conf` file (which would point to the haproxy log files on disk) and possibly trigger a config reload of promtail. In this way, the configuration for each individual service can be handled by the service itself, instead of having to merge all the configs into a single config that gets deployed when promtail does.

**Comment by osandum** [comment]
@bnewbold installing with Ansible, could you possibly make use of the [assemble module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assemble_module.html) to achieve the same thing?

**Comment by cstyan** [comment]
We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point. While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.

Additionally, the Agent's [Flow](https://grafana.com/docs/agent/latest/flow/) configuration model is component-based  that supports combining multiple config files for the single agent binary.

**Comment by chaudum** [comment]
Closing this issue as we don't develop Promtail any further. It is superseded by [Grafana Alloy](https://grafana.com/docs/alloy/latest/). Please report the issue [there](https://github.com/grafana/alloy).
