### ISSUE TITLE
Error parsing pods labels when a label contains a digit in promtail agents

### ISSUE THREAD

**Issue by mel1nn** [grafana/loki#5195]
**Describe the bug**
I have a problem in the promtail agents concerning a bad parsing of labels.

**To Reproduce**
Install Loki and Promtail.
Add a label in a pod with a digit

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: lokiStack via Helm

**Screenshots, Promtail config, or terminal output**
level=error ts=2022-01-20T09:44:23.803162082Z caller=client.go:294 component=client host=loki-stack:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): Error parsing labels '{5g_interface=\"register\", app_kubernetes_io_instance=\"jl-wef\", app_kubernetes_io_managed_by=\"Helm\", app_kubernetes_io_name=\"jl-wef-amf-register\", container=\"jl-wef-amf-register\", filename=\"/var/log/pods/jeanluc_jl-wef-amf-register-6b8cf8dd-q5zkb_62a944e9-66a1-44ce-a9f9-a24d3c7bc056/jl-wef-amf-register/5.log\", helm_sh_chart=\"5g-amf-2.7.0\", job=\"jeanluc/jl-wef-amf-register\", namespace=\"jeanluc\", nf=\"amf\", pod=\"jl-wef-amf-register-6b8cf8dd-q5zkb\", pod_template_hash=\"6b8cf8dd\", product=\"wef\", stream=\"stdout\"}' with error: 1:2: parse error: unexpected character inside braces: '5'"

**Comment by littlepangdi** [comment]
Hi, I am concerned about this compatibility, and have found the cause:
this issue is caused by different guidelines for defining labels in kubernates and prometheus.
* Kubernates allows users add labels to pod in form of [a-z0-9A-Z]*
* Prometheus allows labels matching the regex [a-zA-Z_][a-zA-Z0-9_]* only.

Loki follows Prometheus in processing of labels, so labels start with digit will cause error in loki processing.

Problem is that, is this should be fixed in Prometheus project or here ?
