### ISSUE TITLE
Cortex TableFormatter and how to use it succesfully with DynamoDb

### ISSUE THREAD

**Issue by AlessandroEmm** [grafana/loki#526]
Hey there

Is there any recent example of how to prepare the tables on dynamodb without raising limits? I looked at the ksonnet example but that wouldn't work with recent releases, and as I'm using helm i cannot relate to everything. :-)

I got it to create tables but, it tries to create over 2000 tables which obviously break the limits of dynamodb tables per account. So i must be doing wrong, but looking at calculateExpectedTables() in https://github.com/cortexproject/cortex/blob/master/pkg/chunk/table_manager.go didn't help much without knowing about how things are utilized by loki.

I tried to start it locally via:

` docker run -it -e AWS_REGION=eu-central-1 grafana/cortex-table-manager:r55-b7274ccd --chunk.storage-client=aws --dynamodb.original-table-name=k8s-logs-_index  --dynamodb.use-periodic-tables=true --dynamodb.periodic-table.prefix=k8s-logs-_index_ --dynamodb.chunk-table.prefix=k8s-logs-_chunks_   -dynamodb.url=dynamodb://eu-central-1`

Any working example greatly appreciated.

Thanks
Alessandro

**Comment by daixiang0** [comment]
ping @yubozhao

**Comment by yubozhao** [comment]
@AlessandroEmm There is a bug with the upstream project.  Dont use period table

**Comment by daixiang0** [comment]
@yubozhao is there any process or track about this upstream bug? Need mark it in docs?

**Comment by yubozhao** [comment]
@daixiang0 I haven't have time to keep track of the bug upstream or working with Loki, so I am not sure what is the current status.  I do understand the issue and work around, let me share it here so others can avoid it.

The issue was/is if you are using the period rotating table feature from table manager, the table manager will use the 1970-01-01 as starting time instead of what you configured with.  That's why it will create over 2000 tables, since there are more than 2000 weeks passed.  

The work around for Loki, right now, is don't rotate your index table...

**Comment by daixiang0** [comment]
@yubozhao cool, thanks

**Comment by AlessandroEmm** [comment]
Will _not_ do for now. Thanks.
