### ISSUE TITLE
promtail doesn't scrape init containers

### ISSUE THREAD

**Issue by dguendisch** [grafana/loki#575]
**Describe the bug**
promtail successfully scrapes all my pod's containers log files except for the init containers of my pods.
I tried with the "default" scrape config from here https://github.com/grafana/loki/blob/master/production/helm/promtail/values.yaml as well as with a minimal config.
I deployed promtail as a DaemonSet and checked the new service discovery page at my-promtail:3101/service-discovery (even on all nodes in my cluster), but independent of being dropped or not, there is not even a single "Discovered Label" set listed which would point to an init container.
(Hint: I tested on a k8s 1.13.5 cluster and I exec'ed into the promtail pods and checked the /var/log/pods folder and the init container logs are present just in the same way other containers logs are present there on the filesystem.)

**To Reproduce**
You can use this simple logging pod as an example pod: 
[log-pod.yaml.zip](https://github.com/grafana/loki/files/3174082/log-pod.yaml.zip)

**Expected behavior**
Init containers to be scraped as well.

**Comment by Kuqd** [comment]
I think `initContainers` are skipped from prometheus kubernetes discovery:

```golang
	for _, c := range pod.Spec.Containers {
		// If no ports are defined for the container, create an anonymous
		// target per container.
		if len(c.Ports) == 0 {
			// We don't have a port so we just set the address label to the pod IP.
			// The user has to add a port manually.
			tg.Targets = append(tg.Targets, model.LabelSet{
				model.AddressLabel:    lv(pod.Status.PodIP),
				podContainerNameLabel: lv(c.Name),
			})
			continue
		}
		// Otherwise create one target for each container/port combination.
		for _, port := range c.Ports {
			ports := strconv.FormatUint(uint64(port.ContainerPort), 10)
			addr := net.JoinHostPort(pod.Status.PodIP, ports)

			tg.Targets = append(tg.Targets, model.LabelSet{
				model.AddressLabel:            lv(addr),
				podContainerNameLabel:         lv(c.Name),
				podContainerPortNumberLabel:   lv(ports),
				podContainerPortNameLabel:     lv(port.Name),
				podContainerPortProtocolLabel: lv(string(port.Protocol)),
			})
		}
	}
```

Make sense for prometheus, but I agree for Loki we would like to get logs from those too.

**Comment by daixiang0** [comment]
implement a new k8s discovery interface for Loki?

**Comment by sh0rez** [comment]
Working on this over at the prometheus side, once this is merged, the changes to Loki should be minimal, if any. See prometheus/prometheus#5598

**Comment by sh0rez** [comment]
Looks like we are having a serious dependency problem here ...

https://github.com/grafana/loki/blob/922f1daf5d1780c3b96b0cb7b150f1fe65379262/pkg/promtail/targets/filetargetmanager.go#L21

In `filetargetmanager.go` we have a single dependency on package `relabel`, which has been removed in favor of `pkg/relabel` in prometheus/prometheus#4083.

As the changes of prometheus/prometheus#5598 are required to close this one, we have to update the prometheus vendor to latest `master`.

But running `dep ensure -update github.com/prometheus/prometheus` fails of course, because of the subpackage `relabel` missing. How to deal with this @Kuqd @slim-bean?

**Comment by Kuqd** [comment]
have you tried to change the import statement first ? you could try to use an override also from dep.

**Comment by sh0rez** [comment]
@Kuqd Yes, I tried switching it to `pkg/relabel`, but this package has a different API and I hadn't the time to dig through prometheus PR's yet.

Regarding [overwrites](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#override), I don't understand how they could possibly help here. They seem to allow forcing a specific package version, even if the constraints disallow it .. which does not help because we would break `filetargetmanager.go`? Or do I miss something?

**Comment by Kuqd** [comment]
now you might right, haven't really look at the change. Let me know if you need me to take over.
