### ISSUE TITLE
Promtail to support validating JSON before sending off to Loki

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/loki#5784]
**Is your feature request related to a problem? Please describe.**
When logs are generated in JSON format and sent of to Loki, it happens sometimes that logs are not in valid JSON format. For example this could be due to misconfigured applications typically; init and "sidecar" containers; bugs, misconfiguration of the agent, or any reason. 

This means that logs are ingested, potentially at cost and immediately ignored again when querying them. 

It would be ideal if in promtail drop stage, there could be the option to validate if a logline is in valid JSON format, and if not, just drop it there and never send it off. 

Although there is an existing Promtail JSON stage, it assumes the logline is already in valid JSON format and does not give you the option to drop invalid/unparsable JSON log lines. 

**Describe the solution you'd like**

In promtail drop stage, to have the ability to specify that the logline should pass the "valid JSON parsable check", and if it fails, then drop the log line. 

**Describe alternatives you've considered**
There isn't really an alternative at the moment. You are sort of forced to ingest invalid JSON log lines and then immediately discard them at query time. However this means you're paying costs to ingest and store. 

**Additional context**
None

**Comment by mrmartan** [comment]
It would also be useful to be able to emit the count of invalid logs as a metric.

**Comment by 09jvilla** [comment]
Can some of the folks who thumbs up'd this issue help give some examples of why log lines are generated in invalid JSON format?

**Comment by mrmartan** [comment]
Sometimes they are not json at all. Imagine scraping from a pod with multiple containers, some you have under control (those can be misconfigured), other you don't (3rd party sidecars or init containers that even dont have the ability to write logs in json, e.g. injected service mesh overlay). 

Managing the log shpping middlewares in a larger organizations you run into these situations and this could generate a lot of unusable data before rectified, if it can be.

**Comment by 09jvilla** [comment]
And you don't find yourself using any of those non-json logs @mrmartan ? You wouldn't be able to use the json parser to pull out information for these lines, but you could still manipulate them with the regex or the pattern parser.

**Comment by mrmartan** [comment]
I would though I don't know I can. I am getting JSON perse error entries in Loki/Grafana. Which means I don't have the labels I want attached. Is it possible to setup branching pipelines in primtail?

That's a bit off-topic. The pipeline configuration expects JSON log lines and isn't getting it and then ships unprocessed log lines to storage. It is valid to not want them shipped, isn't it? It is also necessary to be aware that this is happening.

**Comment by 09jvilla** [comment]
> It is also necessary to be aware that this is happening.
Makes sense that you'd want to be aware this is happening. 

>  It is valid to not want them shipped, isn't it? I
I could see it both ways. Its possible you could want the log lines - even if lacking some labels - because that at least gives you some information, even if its not as readily searchable as something properly formatted. If you drop it, any information in that line disappears. 

Just stepping back, apologize if my comments came off as rude. Just trying to understand a bit more about the use case and what's causing it, and understand how prevalent this is in the broader community. Fwiw, we think this will be pretty straightforward to do so we've added it to our backlog.

**Comment by mrmartan** [comment]
@09jvilla Sorry for responding so late. I missed the notification. I was made aware that this will be in a future release of the agent.

> I could see it both ways. Its possible you could want the log lines - even if lacking some labels - because that at least gives you some information, even if its not as readily searchable as something properly formatted. If you drop it, any information in that line disappears.

I can see it both ways as well. In our broader context that is less desirable than dropping them. We are building our own platform and shipping the logs anyway basically skips our governance on ingestion. Also our dashboards are setup so that they expect JSON and the current version only leads to vast amount of JSON parse errors.
