### ISSUE TITLE
Any plan for Store Index in ElasticSearch

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#606]
Loki current support index storage like Cassandra, BoltDB. 

I'm curious if it has plan to support index storage in ElasticSearch? We have a plan to try Loki in Production, want to compare the performance with different storage.
If no, is there some guild that I can follow to implement one?

**Comment by Kuqd** [comment]
Hello @mizeng ,

I don't think we will add index in Elasticsearch, mostly because it's difficult to operate which at the end of the day adds more complexity to your Loki deployments.

That said, I understand that you want to try Elasticsearch as index store. You should start by reading about cortex architecture https://github.com/cortexproject/cortex/blob/master/docs/architecture.md , then look at this interface, that's the one you would need to implement : https://github.com/cortexproject/cortex/blob/master/pkg/chunk/storage_client.go#L6

You can use Cassandra example : https://github.com/cortexproject/cortex/tree/master/pkg/chunk/cassandra

If that answer your question feel free to close this issue.

C
