### ISSUE TITLE
grafana/loki-podman-driver

### ISSUE THREAD

**Issue by yosiasz** [grafana/loki#6279]
**Is your feature request related to a problem? Please describe.**
Many migrating towards podman. Would like to capture logs from such containers using Loki

**Describe the solution you'd like**
a driver specific to podman. grafana/loki-podman-driver

**Describe alternatives you've considered**
Tailing using custom code to use 
https://docs.podman.io/en/latest/markdown/podman-logs.1.html

**Comment by Khalu** [comment]
Hello, while it may not be quite as useful as the docker log driver Podman has some options for logging that are supported in Promtail, like logging to journald and writing to a cri file. I've written about it a bit [here.](https://github.com/Khalu/Podman_logs_to_loki)

**Comment by cstyan** [comment]
Hello, thanks for your feature request! As others have mentioned, there are existing options for getting logs from docker.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.
