### ISSUE TITLE
Allow includes in configuration files

### ISSUE THREAD

**Issue by Nudin** [grafana/loki#6404]
**Is your feature request related to a problem? Please describe.**
When the configuration of Loki or Promtail is generated by multiple parts of provisioning tools (for example different ansible roles or playbooks), it is error-prone to write the configuration into one file.

**Describe the solution you'd like**
A common feature is to allow to include/import files from a `.d`-folder. In the main configuration file one is able to add something like:
```
include /etc/promtail/conf.d/*
```
And the content of all files in the folder will be read and processed as if it were part of the main file.

**Describe alternatives you've considered**
Hard code a folder path.

**Additional context**

**Comment by rabbipigeon** [comment]
I think This feature would be extremely welcomed.

The Problem presents itself more when trying to manage a large number of servers that have slightly varying configurations. It would be nice to have something link a `/etc/promtail/conf.d/basic` thats like a generic configuration then each server might have a customised `/etc/promtail/conf.d/custom` for specielized servers/operations.

**Comment by cedsana** [comment]
I agree the following would be ideal.
```
include /etc/promtail/conf.d/*
```

At first I thought `file_sd_config` ([here](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#file_sd_config)) would allow me to have this kind of dynamic scrape_configs but it's only meant for targets and not configuration.  
My end goal really is to have different individual parts managed by their own modules.  

For example:  
I'm installing and configuring `nginx` using my `nginx` Ansible role and drop a `nginx.yml` into `/etc/promtail/conf.d` that contains all the relevant information, labels, pipelines that are needed and managed by that dedicated `nginx` role.

**Comment by B3nBeng** [comment]
This feature would be really useful.

I don't know if this tips can help you, but I use a workaround which involves to edit **/etc/systemd/system/promtail.service** : 

`ExecStart=bash -c '/usr/bin/promtail -config.file <(cat /etc/promtail/*.yml)'` 
(_Don't forget to run `systemctl daemon-reload`_)

Instead of use only "config.yml" which be limited when we need to managing a lot of servers with different configurations, I use a first file with config base, "e.g. 00-syslog.yml", and multiples others specifics files (e.g. 01-nginx.yml or 02-postgres.yml). I concatenate all of them in the mechanism of "Process Substitution". 
Process substitution uses /dev/fd/xx files to send the results of the process(es) within parentheses to another process.[***](https://tldp.org/LDP/abs/html/process-sub.html)

I use this file in argument of "-config.file" in promtail service.
With `systemctl status promtail`, the command should look like `/usr/bin/promtail -config.file /dev/fd/63`
In my case, **/dev/fd/63** is the stdout of "cat /etc/promtail.*.yml".

**Comment by cstyan** [comment]
Hello, thanks for your feature request.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail. On top of that, the agent already supports this sort of multi config file importing.
