### ISSUE TITLE
Consider use `fasthttp` instead of `net/http` in promtail client

### ISSUE THREAD

**Issue by Dentrax** [grafana/loki#6465]
**Is your feature request related to a problem? Please describe.**
[fasthttp](https://github.com/valyala/fasthttp), one of the mostly used http framework, tuned for high performance and zero memory allocations in hot paths. It's up to 10x faster than builtin `net/http`. [^1] It would be nice to give it a try and do some benchmarks. 

**Describe the solution you'd like**
Replace `net/http` with `fasthttp` in [promtail client](https://github.com/grafana/loki/blob/f80e487dcf106a6c4ea0a82d8afe7b0104addbc3/clients/pkg/promtail/client/client.go#L389).

**Describe alternatives you've considered**
Use `net/http` as it is.

**Additional context**
`-`

I can give a hand on this. But don't know how to apply benchmark test. Do you use any benchmarking strategies on the pipeline or as a separated project?

[^1]: https://github.com/valyala/fasthttp#http-server-performance-comparison-with-nethttp=

**Comment by dannykopping** [comment]
@Dentrax thanks for the feature request.
Can you give us some specifics of the performance issues you're experiencing in your promtail deployment, which lead to this FR being created? Do you have some profiles to share maybe?

**Comment by cstyan** [comment]
Hello, thanks for your feature request.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.
