### ISSUE TITLE
Questions on promtail metrics

### ISSUE THREAD

**Issue by adeverteuil** [grafana/loki#6553]
**Describe the bug**

I want to monitor promtail (or the logs instance in the Grafana Agent) to track data rates and potential issues with connectivity to Loki.

**To Reproduce**

Checking what metrics are available and what's the help string.

For Grafana Agent metrics:
`curl localhost:12345/metrics`

For Promtail metrics:
`curl localhost:9080/metrics`

**Expected behavior**
A clear and concise description of the metrics.

**Environment:**
 - Infrastructure: Ubuntu 22.04 VM
 - Deployment tool: Ansible
 - Promtail version: v2.4.2
 - Grafana Agent version: v0.24.1

**Questions**

Are these duplicates? Shouldn't they be counters?

```
# HELP promtail_file_bytes_total Number of bytes total.
# TYPE promtail_file_bytes_total gauge
promtail_file_bytes_total{logs_config="default",path="/var/log/prometheus/query.log"} 1.4518576e+07
# HELP promtail_read_bytes_total Number of bytes read.
# TYPE promtail_read_bytes_total gauge
promtail_read_bytes_total{logs_config="default",path="/var/log/prometheus/query.log"} 1.4518576e+07
```

Here, the HELP line should say "Number of active targets".

```
# HELP promtail_targets_active_total Number of active total.
# TYPE promtail_targets_active_total gauge
promtail_targets_active_total{logs_config="default"} 1
```

Is this the number of log messages read? Sent to stdout? Sent to Loki?

```
# HELP log_messages_total Total number of log messages.
# TYPE log_messages_total counter
log_messages_total{level="debug"} 5.792071e+06
log_messages_total{level="error"} 1
log_messages_total{level="info"} 4.821346e+06
log_messages_total{level="warn"} 3
```

What does status_code="-1" mean?

```
# HELP promtail_request_duration_seconds Duration of send requests.
# TYPE promtail_request_duration_seconds histogram
promtail_request_duration_seconds_bucket{host="localhost:3100",status_code="-1",le="0.005"} 0
...
```

**Comment by MasslessParticle** [comment]
Thanks for your feedback!

- `promtail_file_bytes_total` reports the total bytes for the file being read which is indicated by the `path` label. It's a gauge because the file at `path` can be a variable size
- `promtail_read_bytes_total` is the number of bytes that have been read from the file indicated by the `path` label. It should always be <= `promtail_file_bytes_total` for the same `path`
- `log_messages_total` is the total number of log messages that prometheus has logged on it's own behalf.
- Status code `-1`  in `promtail_request_duration_seconds` indicates that there was an error making the request such that no valid status was returned.
