### ISSUE TITLE
Promtail support for encrypted logs in kafka 

### ISSUE THREAD

**Issue by smbgray** [grafana/loki#6584]
**Is your feature request related to a problem? Please describe.**
On some environments there is a need to send logs via kafka encrypted with Symmetric-key algorithms (f.e. AES256).

**Describe the solution you'd like**
Make promtail support decryption of encrypted(Symmetric-key) messages from kafka.

**Comment by cstyan** [comment]
Hello, thanks for your feature request.

We're currently reevaluating promtails position as a project within Grafana Labs. Internally we're actually using the [Agent](https://github.com/grafana/agent) for both metrics and logs collection at this point.

While we haven't made a formal decision yet, we expect in the near future that all new feature work will be done in the Agent's log collection pipelines rather than in Promtail.
