### ISSUE TITLE
[ruler]: GeneratorURL in alerts is wrong/unuseful 

### ISSUE THREAD

**Issue by badrabubker** [grafana/loki#6743]
**Describe the bug**
Loki ruler usesd to use  `github.com/cortexproject/cortex/pkg/ruler` to send alert using the `SendAlerts` function and it was moved to `pkg/ruler/base/`.
The SendAlerts function in cortex package assumes the alert was created from a Prometheus-like system i.e one can see the generating rule under `externalURL + /graph?.....`, however this is not the case for loki

Alerts sent from loki (even if externalURL is set correctly) will have unuseful GeneratorURL

Since grafana is the main user frontend for loki, this might be a bit tricky to solve, however with loki 2.6.0 and the ability to query all tenants at once this can be achieved by redirecting to the global datasource which can query all tenants   

**To Reproduce**
1. Started Loki with ruler enabled (2.61)
2. Set -ruler.external.url 
3. Write some rules to trigger some alerts

**Expected behavior**
Alert with a useful GeneratorURL field i.e clicking on the link will redirecting me to a UI where I see the expression and result 

**Environment:**
 - Infrastructure: any
 - Deployment tool: any

**Screenshots, Promtail config, or terminal output**
N.A

I will be happy to send a PR. My approach will be to modify SendAlerts function to template a grafana link

Thanks

**Comment by spirkaa** [comment]
Any news on this?

**Comment by aminesnow** [comment]
Hi there @badrabubker, I'm taking a look at this issue in order to see what possible solution we can have. You suggest to fix the URL and have it redirect to the "global datasource" in Grafana. 

The issue I see with this is that it assumes that there is a "global datasource" setup in Grafana, and even then, Loki has no idea what that datasource is, so when the user is redirected to Grafana, they may still have to pick the "global datasource" in order to see the query and the results.

Am I missing something here? Or is this the intended solution you're suggesting?
