### ISSUE TITLE
loki-mixin: The job selector should be configurable for the generated grafana dashboards

### ISSUE THREAD

**Issue by sandhose** [grafana/loki#678]
I planed to use the `loki-mixin` as a dependency of my jsonnet project that builds all our dashboards and prometheus rules, but I noticed the dashboard have their selector hard-coded.

https://github.com/grafana/loki/blob/aecf86760574f189a7af9a719124f91808b8e764/production/loki-mixin/dashboards.libsonnet#L159

For example, in my case, i'd like the selector to look like `{job="promtail", namespace="$namespace"}`, instead of `{job="$namespace/promtail}`.

This is done for example in `kubernetes-mixin` by having a `_config` object with each selector. This way it can be overridden when importing the mixin.

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/30468e58fbdda54af49d12f8325195ee3547dd27/config.libsonnet#L4-L18

**Comment by sh0rez** [comment]
Started working on this, however as it turns out, this is not as simple to implement as it sounds.

**1. Regex**
This code
```diff
diff --git a/production/loki-mixin/dashboards.libsonnet b/production/loki-mixin/dashboards.libsonnet
index b1aaaf8..7128e2b 100644
--- a/production/loki-mixin/dashboards.libsonnet
+++ b/production/loki-mixin/dashboards.libsonnet
@@ -11,7 +11,7 @@ local utils = import "mixin-utils/utils.libsonnet";
         g.row('Frontend (cortex_gw)')
         .addPanel(
           g.panel('QPS') +
-          g.qpsPanel('loki_request_duration_seconds_count{cluster=~"$cluster", job=~"($namespace)/cortex-gw", route="api_prom_push"}')
+          g.qpsPanel('loki_request_duration_seconds_count{cluster=~"$cluster", %(cortexGwSelector)s, route="api_prom_push"}' % $._config)
         )
         .addPanel(
           g.panel('Latency') +
@@ -22,7 +22,7 @@ local utils = import "mixin-utils/utils.libsonnet";
         g.row('Distributor')
         .addPanel(
           g.panel('QPS') +
-          g.qpsPanel('loki_request_duration_seconds_count{cluster=~"($cluster)", job=~"($namespace)/distributor"}')
+          g.qpsPanel('loki_request_duration_seconds_count{cluster=~"($cluster)", %(distributorSelector)s}' % $._config)
         )
         .addPanel(
           g.panel('Latency') +
```

includes regex matching (`label_replace`), which requires capture groups in the selector. This is impossible to infer from the selector. Maybe we could `dict` selectors here:
```jsonnet
distributorSelector: {
  'plain': 'job=~"$namespace/distributor"}',
  'regex': 'job=~"($namespace)/distributor"}',
}
```
**2. `util`**
Some selectors are written using helpers like `util.selector.eq`. However, this library requires supplying the selector as name and value separately. `kubernetes-mixin` does not use this, so we cannot steal a solution there. 

Possible options:
* Rewrite the selector to string form in case this is possible? Would be the most simplest. @slim-bean 
* Parse the string to create arguments (lot of work)
* Pass the argument form in the dict as well

**Comment by chancez** [comment]
Related: https://github.com/grafana/loki/pull/1978
