### ISSUE TITLE
Unable to build logcli

### ISSUE THREAD

**Issue by jgaa** [grafana/loki#693]
**Describe the bug**
I am unable o build the log client on Ubuntu 18.04 with `go version go1.12.6 linux/amd64`

**To Reproduce**
```
:~/src/loki$ go build ./cmd/logcli/
# _/home/jgaa/src/loki/cmd/logcli
cmd/logcli/client.go:77:43: not enough arguments in call to config.NewClientFromConfig
        have (config.HTTPClientConfig, string)
        want (config.HTTPClientConfig, string, bool)
```

**Comment by sandlis** [comment]
@jgaa I guess you have updated github.com/prometheus/common or your go environment is picking up dependencies from vendor folder since I can see config.NewClientFromConfig from vendor/github.com/prometheus/common accepts only 2 params while latest master from github.com/prometheus/common accepts 3 params for same function.
Heres the function from vendor:
https://github.com/grafana/loki/blob/master/vendor/github.com/prometheus/common/config/http_config.go#L116

Heres the function from prometheus master:
https://github.com/prometheus/common/blob/master/config/http_config.go#L125

**Comment by jgaa** [comment]
My environment was probably not setup correctly. I ended up getting the binary client.
Thank you for the very quick response.

**Comment by funkycode** [comment]
it is still relevant when importing loki client
you didn't hanlde v2 support on import and at the same time you can't compile:
`# github.com/grafana/loki/pkg/logcli/client
../../../../go/pkg/mod/github.com/grafana/loki@v1.6.1/pkg/logcli/client/client.go:186:68: cannot use false (untyped bool constant) as config.HTTPClientOption value in argument to config.NewClientFromConfig`

**Comment by tathagatachowdhury** [comment]
I am also facing same error when I try to build my service:

```pkg/mod/github.com/grafana/loki@v1.6.1/pkg/promtail/client/client.go:133:69: cannot use false (untyped bool constant) as config.HTTPClientOption value in argument to config.NewClientFromConfig```

Is there any way to handle this?
