### ISSUE TITLE
Loki Pod Log Error - table_manager - InvalidParameter - TagResourceInput.Tags missing

### ISSUE THREAD

**Issue by anders-ni** [grafana/loki#702]
**Describe the bug**
Error being logged into the loki pod logs 
`level=error ts=2019-06-26T15:58:34.40020321Z caller=table_manager.go:174 msg="error syncing tables" err="InvalidParameter: 1 validation error(s) found.\n- missing required field, TagResourceInput.Tags.\n"` 
Unclear what TagResourceInput.Tags may be missing or where to add them. 

**To Reproduce**
1. Upgrade from loki hash 866a126 to 4c71382
2. Using a DynamoDB for AWS storage, not created by table_manager (both now and prior to upgrade)
3. Included the new default config values for table_manager in loki/values.yaml 
```  
table_manager:
    retention_deletes_enabled: false
    retention_period: 0
```
4. Successfully deployed, updated pods to Statefulset instead of deployment, and Promtail to new daemonset
5. Logs from pods are collected and available in Grafana as expected. However this error is produced in the loki pods every 2 minutes.  `level=error ts=2019-06-26T15:58:34.40020321Z caller=table_manager.go:174 msg="error syncing tables" err="InvalidParameter: 1 validation error(s) found.\n- missing required field, TagResourceInput.Tags.\n"`

**Expected behavior**
No error should be logged, as everything appears to be functioning as expected. Unclear what TagResourceInput.Tags may be missing or where to add them. 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
```
level=info ts=2019-06-26T15:58:32.400004243Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=1 expected_tables=1
level=error ts=2019-06-26T15:58:34.40020321Z caller=table_manager.go:174 msg="error syncing tables" err="InvalidParameter: 1 validation error(s) found.\n- missing required field, TagResourceInput.Tags.\n"
```

**Comment by sandlis** [comment]
@anders-ni Are you using dynamodb? I think it has something to do with dynamodb Tags? Have you defined them?
https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/chunk/schema_config.go#L318

**Comment by temal-** [comment]
I got the same scenario and problem with a self-created dynamodb on `v0.2.0`.

What are these tags supposed to look like, @sandlis?

**Comment by sandlis** [comment]
@temal- They are supposed to be `key=value` pairs. I haven't tried them but looking at following links I feel that is how they are supposed to be defined.

https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/chunk/schema_config.go#L325
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tagging.Operations.html

It would be great if you can give it a try and share how it goes.

**Comment by temal-** [comment]
Ah, I think I got it. When I add tags to the dynamodb table I also have to define them in the loki configuration?

When I delete the tags on the dynamodb table (that I set there manually), the error message disappears.

**Comment by sandlis** [comment]
Maybe, can't tell for sure. Error message atleast says so when they need to be set.
So It seems its not actually an issue in Loki. Closing this.

**Comment by temal-** [comment]
Where/how do I define the tags in the loki configuration?

The error message is thrown by loki but it isn't an issue in loki? I don't understand.

**Comment by sandlis** [comment]
Ohh, sorry about that. I thought it worked for you.
It would go under `schema_config` -> `configs` -> `index`
For example, if I would use dynamodb [here](https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml#L23-L25), I would change it to following:
```
    index:
      prefix: index_
      period: 168h
      tags:
        key: value
```

**Comment by temal-** [comment]
It worked after I removed the tags, but I want to keep the tags. ;)

Thanks a lot. Now it's working!

**Comment by tom-butler** [comment]
Does Loki use these tags? I don't really understand why I need to duplicate the tags my org requires for cost splitting into the app that is using the table.

**Comment by sandeepsukhani** [comment]
Sorry, I am not an expert in Dynamodb but I guess you can define different tags for Loki tables.
I am not sure if that is what you are looking for.

**Comment by tom-butler** [comment]
Sorry, I'll explain a little bit better.

I've created a DynamoDB table which is a resource in AWS, my org requires us to add a series of tags to all AWS resources that support tags so we can accurately identify owners, track costs etc. 

I don't understand why I need to tell Loki about all of these tags, when I'm already identifying the table by the prefix, does it need these tags for bootstrapping and connecting to the table? or does it use these tags as part of the Loki metadata index operations?

Some of the other tools I've worked with (Kubernetes cluster autoscaler) require a single tag, that they use to identify resources that they should control, but it seems like Loki wants to know about all the tags I've configured on my DynamoDB Table.

This means my Loki cluster will probably break for a few minutes when my Infrastructure as Code is deploying updates to our cost tags when they change each year.

I'm not sure if I correctly understand what Loki is expecting, which is why I'm asking for some more clarification. 

If it does require all tags in it's config I'd like to propose some alternatives to that design decision as it breaks the principles of least astonishment. If it is used in Loki for some reason I'm not aware of, it'd be good to include this in the AWS examples section of the docs.
