### ISSUE TITLE
Helm: Single binary and read autoscaling does not work

### ISSUE THREAD

**Issue by ArkadiuszSpiewak** [grafana/loki#7097]
After looking at helm chart and trying to configure autoscaling i noticed that single binary and read templates does not have hpa.yaml templates, and so they do not support autoscaling. But in values.yaml there is setting to enable autoscaling.
Should there be hpa.yaml files for those subcharts?
What is the logic for single binary autoscaling setting?
Also there is reference in comments to `queryIndex.enabled: true` but no such setting is in helm chart.

**To Reproduce**
1. Deploy helm chart with read.autoScaling.enabled: true or singleBinary.autoScaling.enabled: true
2. no pod autoscalers are created

**Expected behavior**
Autoscaling should work. Or values setting autoscaling should not be present in default values.yaml

**Comment by trevorwhitney** [comment]
This is intentional, as we don't currently have a use case for autoscaling. The chart only supports single binary mode for local filesystem backends, and is opionated that any system the needs to scale (ie. is more than 1 node) should use object storage and read/write targets. Currently, both the read and write targets are statefulsets which we don't traditionally autoscale here at GL because of the complications that represents with both provisioning and discarding PVs and PVCs.

Could you describe your use case a little bit more, and how you might solve for some of the problems around auto-scaling statefulsets?

There are plans to add a 3rd target to this chart that deploys just queriers and query-frontends as a deployment rather than a statefulset. That work will include an HPA for that deployment as it will be stateless and seems a good candidate for autoscaling.

**Comment by ArkadiuszSpiewak** [comment]
Current values.yaml [Line 621-631](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L621-L631) and [Line 688-698](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L688-L698) has autoscaling related options. Should they be deleted? otherwise its confusing.

**Comment by rgarcia6520** [comment]
@trevorwhitney Would a read HPA template be doable now with the recent release of chart version `4.0.0` for Loki `2.7.3` and the backend target introduction. Assuming that the installation is using external object storage.

**Comment by KarstenSiemer** [comment]
I came here because I was very confused with the helm chart settings

**Comment by trevorwhitney** [comment]
Is this addressed by https://github.com/grafana/loki/pull/8684?
