### ISSUE TITLE
Querier timeout when reaching ingesters

### ISSUE THREAD

**Issue by Kuqd** [grafana/loki#718]
Currently there is no timeout when doing GRPC between ingesters and querier.

This leads to the querier stacking and starving goroutines until it gets restarted.

It is only happening when ingesters are unresponsive.

We should have a timeout for that connection.

**Comment by sh0rez** [comment]
Sure?

It looks like the `querier` configures its `IngesterClient` using `t.cfg.IngesterClient` config:
https://github.com/grafana/loki/blob/1c95a5b0e7c6bfa809c3ab1c737bd22e4189d27f/pkg/loki/modules.go#L135-L136
https://github.com/grafana/loki/blob/1c95a5b0e7c6bfa809c3ab1c737bd22e4189d27f/pkg/querier/querier.go#L40-L42

But this one does include a timeout:
https://github.com/grafana/loki/blob/1c95a5b0e7c6bfa809c3ab1c737bd22e4189d27f/pkg/ingester/client/client.go#L22

And this timeout defaults to `5s` because of its flag:
https://github.com/grafana/loki/blob/1c95a5b0e7c6bfa809c3ab1c737bd22e4189d27f/pkg/ingester/client/client.go#L31

So did I miss another place where a timeout is required?

**Comment by Kuqd** [comment]
I don't think this is used. But what is missing mostly is a query timeout for instance:

```
clientDeadline := time.Now().Add(time.Duration(*deadlineMs) * time.Millisecond)
ctx, cancel := context.WithDeadline(ctx, clientDeadline)
```

And for most of queries this is not there.

**Comment by pracucci** [comment]
@Kuqd I would be glad to pick from here and work on a PR. Few questions, please:
1. Should we allow to set the query timeout via querier config flag, or should be possible to override it via HTTP request too?
2. Should the `Label()` request have a different timeout than `Query()`? If yes, may `-querier.logs-query-timeout` and `-querier.labels-query-timeout` work?
3. Any suggestion on how we should unit test it?

**Comment by Kuqd** [comment]
Yes please.

1 - Only via a config flag with a sane default.
2 - Label and Query should be the same.
3 - I'm not sure this would be necessary be if you achieve it, I'll take it.

Thanks @pracucci
