### ISSUE TITLE
When is the next promtail release?

### ISSUE THREAD

**Issue by rabun788** [grafana/loki#7354]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**

We hit the gcplog pubSub issue every 30 minutes. Wondering when it will be released.

https://github.com/grafana/loki/pull/6965

**Comment by dannykopping** [comment]
Hey @rabun788

It'll likely be released in the next couple weeks.
If you need to work around this issue, we publish weekly releases (numbered `kXXX` where `XXX` = the week number since we started this scheme, right now it's `118`) and these weekly releases are the basis for the actual releases; we pick one that is stable and has been running in our environment for a while.

This `k118` release is a contender to be `v2.7` so it's safe to use it for now.
