### ISSUE TITLE
Helm Chart: Loki canary should not be deployed if selfMonitoring.enabled is false

### ISSUE THREAD

**Issue by balonik** [grafana/loki#7364]
**Describe the bug**
Currently the template for Loki Canary daemonset only checkes for `.Values.monitoring.selfMonitoring.lokiCanary.enabled`.
Because it is under `monitoring.selfMonitoring` it should check for `.Values.monitoring.selfMonitoring.enabled` as well.

**To Reproduce**
Deploy Loki using Helm Chart with `monitoring.selfMonitoring.enabled=false`. Loki Canary daemonset is created.

**Expected behavior**
Deploy Loki using Helm Chart with `monitoring.selfMonitoring.enabled=false`. Loki Canary daemonset is NOT created.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by towolf** [comment]
Actually I like the Canary component, but the self-monitoring requires grafana-agent and CRDs, which we do not do.

So, I would prefer them to be separate.

**Comment by trevorwhitney** [comment]
Yeah, I tend to agree with @towolf that there will be many who want the canary without the self monitoring. The canary is useful even if you don't scrape it's logs and just rely on it's metrics, and many will have installations where they have their own metric scraping configs independent of the included self monitoring ones.

Perhaps the real issue here is the nesting of the config. Maybe instead we should promote the `lokiCanary` config to a top level section, outside of `selfMonitoring`? I can see the separation being and custom resources to actually scrape the canary would stay under `selfMonitoring`, but the actual canary deployment is independent.

Thoughts?

**Comment by towolf** [comment]
I fully agree with your proposal.

**Comment by towolf** [comment]
@trevorwhitney I've implemented your suggestion in #7757. Please take a look?

**Comment by trevorwhitney** [comment]
Thanks for the addition @towolf, approved and running the build now.
