### ISSUE TITLE
Docs feedback: /clients/promtail/gcplog-cloud.md

### ISSUE THREAD

**Issue by tpoindessous** [grafana/loki#7819]
Hi

on this webpage ( https://grafana.com/docs/loki/latest/clients/promtail/gcplog-cloud/ ), the schema is now 404 ( https://grafana.com/docs/loki/latest/clients/promtail/gcplog-cloud/gcp-logs-diagram.png ).

Thanks !

**Comment by kavirajk** [comment]
The image should actually comes from one parent path above it.
e.g: this one works
https://grafana.com/docs/loki/latest/clients/promtail/gcp-logs-diagram.png

This is already fixed in https://github.com/grafana/loki/pull/7577

You can see the rendered doc for "next" release (from tip of the main) works just fine.
https://grafana.com/docs/loki/next/clients/promtail/gcplog-cloud/

But you are right, we should fix it on the "latest (2.7.0)" version of the docs as well.

Let me check if there are any easy way to fix that.

**Comment by kavirajk** [comment]
Fixed with above PR. the original link is rendering image without 404 now.
https://grafana.com/docs/loki/latest/clients/promtail/gcplog-cloud/

![Screenshot_2022-12-01_11-59-31](https://user-images.githubusercontent.com/3735252/205036110-04219a80-85f4-4b2c-a3d2-68930999be57.png)

Thanks for reporting the issue @tpoindessous. Closing now.
