### ISSUE TITLE
Release Strategy: docker Tags based on Github releases 

### ISSUE THREAD

**Issue by BouchaaraAdil** [grafana/loki#783]
**Is your feature request related to a problem? Please describe.**
docker Tags, the problem is that i don't know which is the stable docker image, since are not versionned with x.x.x. instead they are with master-${commit-hash}, which is  not best practices are it's noisy for developers, devops ...

**Describe the solution you'd like**
having a clear release versions **x.x.x**, usingTravis CI/ CircleCI since are supporting open source and supporting triggering based on Github Tags and provides you with an env variable that's contain git tag, then use it to push with it docker images ... 

this is much better

**Comment by slim-bean** [comment]
Hello @BouchaaraAdil, there currently only exists one release for Loki v0.1.0 and there is a corresponding tagged docker image for it as well, as is referenced within the helm charts.  The master-${commit-hash} builds are important because that's how our continuous delivery system works.  Given that Loki is a beta project and there is rapid development occurring it's not practical at this time to do a full semver release for every fix/build we make yet it's necessary for us and many in the community to have access to fixes as the show up in master and many don't want to wait for an official release (nor build the images themselves).

We are actively working on the release pipeline at this moment to help improve the cadence of our releases, which will include a release page with proper changelog and links to binaries as well as docker images, most likely this will be the [github release page](https://github.com/grafana/loki/releases).  Hopefully direct links here to the docker images will make it easier to sort through the noise.
