### ISSUE TITLE
Loki loses access to old data after restarting the docker container

### ISSUE THREAD

**Issue by noahsmindfuck** [grafana/loki#8011]
**Describe the bug**
_Background_
I am scraping custom log files on my computer with grafana/promtail and use grafana/loki and grafana/grafana to store and display that data.

_Introduction_
I am trying to figure out the cause of a bug(?) in Grafana, see https://github.com/grafana/grafana/issues/60775, https://github.com/grafana/grafana/issues/59408, where at some point Grafana can not show data anymore although it is present. Slowly I think Loki is the culprit which is why I added an issue in this repository.

_Analysis_
Now I have a running setup with Grafana/Promtail/Loki and I changed some parameters in the Loki config file and restarted the Loki container with docker-compose up -d. When I then try to access the "old" data that was visible in Grafana before all the data points are lost.

**To Reproduce**
See my config files here https://github.com/grafana/grafana/issues/59408#issuecomment-1333712803
1. change a line in the Loki-config.yml
2. restart the docker-compose file with ```docker-compose up -d```
3. reload the Grafana Dashboard and find no data visible or accessible
4. restart the docker-compose file with ```docker-compose up -d --force-recreate```
5. reload the Grafana Dashboard and find all data visible and accessible as long as any data point is in the time after the restart. Whenever I zoom into the past (this is visible) I receive **No Data** on all panels.

**Expected behavior**
Access the data from the log files.

**What happens instead**
Grafana shows **No Data** in all of my fields where the last timestamp in the log file that is scraped is from before the restart of Loki.

**Environment:**
Environment:
Grafana version:
image: grafana/grafana:latest
Data source type & version:
image: grafana/promtail:2.4.0
image: grafana/loki:2.4.0
**also tested with 2.7.0, same issue**
OS Grafana is installed on: MacOS X 10.15.7 (Localhost)
User OS & Browser: MacOS X 10.15.7 & Safari
Grafana plugins: clock-panel
Others:

**Screenshots, Promtail config, or terminal output**
Please find required [screenshots](https://github.com/grafana/grafana/issues/60775#issue-1511827005), [config files](https://github.com/grafana/grafana/issues/59408#issuecomment-1333712803) and so on in the above linked Bug Reports in grafana/grafana issue tracker

**Comment by MichelHollands** [comment]
@noahsmindfuck Is the Promtail container restarted when you run `docker-compose up -d`? If not it will still have the current position in `/tmp/positions.yaml`. Promtail will only read from the current position onward and store those logs in Loki. A Loki restart will clear out everything as you don't store the logs outside of the container as far as I can see.

Feel free to reopen this issue.

**Comment by juzn01** [comment]
hi brother, i cp positions.yaml file and then mount it to container, but i get error when container running like:
caller=positions.go:178 msg="error writing positions file" error="rename /tmp/.positions.yaml6627531535687638438 /tmp/positions.yaml: device or resource busy"
i change premission 777 for it, but error not gone.Do you have any idea for it.
Thanks

**Comment by Renan-Leal** [comment]
I realize this is an old issue and you’ve likely already found a solution. However, since I struggled to find any helpful information on it, I’ll share how I managed to resolve the problem for anyone facing something similar.

I'm not going to show my entire Loki configuration here—just the key parts needed to make it work correctly.

**_loki-config.yaml:_**
```
ingester:
  wal:
    enabled: true
    dir: /tmp/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem
```

In **_Docker Compose_**, I mapped the following volumes for the Loki service:
```
- ./config/loki/loki-config.yaml:/mnt/config/loki-config.yaml
- ./loki-data/wal:/tmp/wal                  # WAL persistence
- ./loki-data/index:/tmp/loki/boltdb-shipper-active  # Index persistence
- ./loki-data/cache:/tmp/loki/boltdb-shipper-cache   # Cache persistence
- ./loki-data/chunks:/tmp/loki/chunks       # Chunks persistence
- ./loki-data/compactor:/tmp/loki/boltdb-shipper-compactor  # Compactor persistence
```

Here's an improved version of your text with enhanced clarity and structure:

I realize this is an old issue and you’ve likely already found a solution. However, since I struggled to find any helpful information on it, I’ll share how I managed to resolve the problem for anyone facing something similar.

I'm not going to show my entire Loki configuration here—just the key parts needed to make it work correctly.

loki-config.yaml:

yaml

ingester:
  wal:
    enabled: true
    dir: /tmp/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem

In Docker Compose, I mapped the following volumes for the Loki service:

yaml

- ./config/loki/loki-config.yaml:/mnt/config/loki-config.yaml
- ./loki-data/wal:/tmp/wal                  # WAL persistence
- ./loki-data/index:/tmp/loki/boltdb-shipper-active  # Index persistence
- ./loki-data/cache:/tmp/loki/boltdb-shipper-cache   # Cache persistence
- ./loki-data/chunks:/tmp/loki/chunks       # Chunks persistence
- ./loki-data/compactor:/tmp/loki/boltdb-shipper-compactor  # Compactor persistence

Additionally, your **_promtail-config.yaml_** should include a section for positions like this:
```
positions:
  filename: /tmp/positions.yaml
```

For the Promtail service in **_Docker Compose_**, the following volumes should be mapped:
```
- ./config/loki/promtail-config.yaml:/mnt/config/promtail-config.yaml
- /var/lib/docker/containers:/host/containers
- ./promtail-data:/tmp
```
Feel free to adjust this to fit your specific context.
