### ISSUE TITLE
Feature Request: [LogQL ] should have a way to filter out duplicate label values

### ISSUE THREAD

**Issue by rkonfj** [grafana/loki#8649]
It's like this:
### Original log lines hava common label `app=order`
```
{"event": "access", "id": "1", "time": "2023-02-28 15:12:11"}
{"event": "access", "id": "1", "time": "2023-02-28 15:13:11"}
{"event": "access", "id": "2", "time": "2023-02-28 15:14:11"}
{"event": "access", "id": "2", "time": "2023-02-28 15:15:11"}
```

### `LogQL` to query logs: ` {app="order"} | json | distinct id `

```
{"event": "access", "id": "1", "time": "2023-02-28 15:13:11"}
{"event": "access", "id": "2", "time": "2023-02-28 15:15:11"}
```

### Context (why I need this feature)
I want to query a user's activity log, but don't want to see duplicate logs for the same user.

**Comment by liguozhong** [comment]
```
count(
       count_over_time(
                        {app="order"} | json
                        [10m])
         by (id)
)
```

**Comment by rkonfj** [comment]
Thanks @liguozhong . 

I need to see the log lines, that is, the `logs query`, not the `metrics query`. Is there a way?

**Comment by liguozhong** [comment]
No

**Comment by liguozhong** [comment]
No

**Comment by liguozhong** [comment]
But you can achieve a similar problem indirectly by using the latest grafana version（may be 9.4）.
It can execute a `Log Query` while querying the `metrics query`, so that you can see the log line.

Similar to the `exemplar` of prometheus, if you have heard of this feature before, you should know what is going on with the characteristics of grafana


![image](https://user-images.githubusercontent.com/9583245/222028949-cead2a63-e9ef-4458-b358-1a2a4554c129.png)

**Comment by liguozhong** [comment]
https://github.com/grafana/loki/pull/7974

There is also a way to solve it directly through loki.
If you have your own fork of the loki code. You can also refer to this PR to try to achieve a similar feature.
This PR can directly solve this problem without going through grafana 9.4.

But this PR is currently closed and will not enter the main branch.
But try not to, trust me. It is a very difficult job to maintain a  code branch continuously and keep in sync with main branch, which is also one of my main tasks。

**Comment by liguozhong** [comment]
Maybe we can discuss whether to implement `| distinct`, sounds like a nice feature, but not yet.

**Question 1:** 

   If | distinct id has a total of 150 different id, but the log query limit is 50, you want to get 150 or 50 at this time？Because the log query must have a limit.

**Difficulties in realizing | distinct**

1: At present, the` | parser` pipeline of the `log query` can only process one line of logs temporarily, and the `by` in the `metrics query` can process the global log. How do we introduce global data into the existing` log query` code?

2: The `shard query` is currently queried in batches according to label %16, but the id in | distinct id is read out in the log using `| json`. This will result in duplicate ids in the final 16 shard queries after deduplication. At this time, if you deduplicate it again, it may cause the final number of logs to be less than the `limit` request.

3:`spit_by_time` also has the same problem


Anyway, we can wait for more eyes to discuss this issue

**Comment by liguozhong** [comment]
nice issue ,thanks @rkonfj

**Comment by liguozhong** [comment]
> Thanks @liguozhong .
> 
> I need to see the log lines, that is, the `logs query`, not the `metrics query`. Is there a way?

hi, I submitted a PR, can you help to see if ie is what you want？

**Comment by hasland** [comment]
@liguozhong Hey, as `distinct` was removed, is there another way that we can achieve it now?

**Comment by liguozhong** [comment]
> @liguozhong Hey, as `distinct` was removed, is there another way that we can achieve it now?

pr：https://github.com/grafana/loki/pull/10356

hi，@hasland,  I am very sorry that my previous code has bug and  was not accepted by the Loki community.

As far as I know, there is currently no other way to achieve similar results.

I was adjusted back to the prometheus team from the loki team last year, but this year I returned to the logging team. I think I still have a chance to engage in the operation / develop of loki. If so, I will come back to the Loki community to re-implement | distinc syntax to Let more community have this powerful feature.

Currently, I use | distinc to implement the logreduce feature of sumo logic, which can quickly discover the pattern distribution of error logs. This should also be used by other people in the loki community.

**Comment by liguozhong** [comment]
> @liguozhong Hey, as `distinct` was removed, is there another way that we can achieve it now?

https://github.com/grafana/loki/pull/10356#issuecomment-1693585855
