### ISSUE TITLE
Grafana - Loki data source receiving 400 Unauthorized error

### ISSUE THREAD

**Issue by Izvi-digibank** [grafana/loki#8675]
**Describe the bug**
Added Loki datasource from Grafana and configured the loki-gateway service url: `http://loki-gateway.loki/`
Then got the following error: `Grafana - Loki data source receiving 400 Unauthorized error`.

NOTE: loki-gateway `basicAuth` is disabled by default, hence no need to add user & password to Loki data source in Grafana.

Tried:
1. Enable loki-gateway `basicAuth` and pass the credentials through Grafana Loki Data Source.
2. Skip tls verification

Both ended up with the same error.

**Expected behavior**
Get 200 authorized. 

**Environment:**
 - Infrastructure: EKS 1.23, Promethues-stack with Grafana v7.3.5, Loki v2.7.3
 - Deployment tool: helm chart

**Logs:**
Loki-gateway Pod:
`10.7.60.60 - - [01/Mar/2023:14:18:53 +0000]  401 "GET /loki/api/v1/label?start=1677679732842000000 HTTP/1.1" 10 "-" "Grafana/7.3.5" "10.7.127.117, 10.0.60.21, 10.0.60.21"`

**Comment by DylanGuedes** [comment]
Hey thanks for your report.
We keep our github issues strictly for reporting problems or for suggesting features. Since this is more like a question I'm closing it. The right places to ask for help are on our public slack or community forum.

Anyway, to not leave you without any help, you're probably missing the XorgID (can't remember the full name) header from your configuration. And as a final suggestion, I recommend running a more recent Grafana version.

**Comment by DylanGuedes** [comment]
on the data source, add a new header named `X-Scope-OrgID` with the same value as the one used by Promtail (by default it is `fake` if I'm not mistaken). In your case it might be `1` based on that last pic.
