### ISSUE TITLE
Set metadata/labels via log files (ingest time)

### ISSUE THREAD

**Issue by sandstrom** [grafana/loki#88]
Most of our services (nginx, application servers, etc) emit JSON lines[1] like this:

```
{ "timestamp" : "2018-12-24T18:00:00", "user-id" : "abc", "request-id" : "123", "message" : "Parsing new user data" }
{ "timestamp" : "2018-12-24T18:01:00", "user-id: " "def", "request-id" : "456", "message" : "Updating user record" }
{ "timestamp" : "2018-12-24T18:02:00", "user-id: " "abc", "request-id" : "789", "message" : "Keep alive ping from client" }
```

We'd need a way to set labels via the promtail agent (basically json parsing and tagging/labeling at ingest-time). In this example that would be the `user-id` and `request-id` metadata. For troubleshooting and debugging we need a way to see the logs for a particular user or request.

[1] http://jsonlines.org/

*(this is partly related to high cardinality labels, but I've split it out into two separate issues, the other one is here: https://github.com/grafana/loki/issues/91)*

**Comment by gouthamve** [comment]
Hmm, would grep not help you select on user-id and request-id? Adding high cardinality labels to the index means it blows up and that is something we want to avoid. We think the trade-off there is to achieve the same selection via grep.

**Comment by ventris** [comment]
If one searches for user-id and find too many logs and needs to append something else to the search to reduce the clutter its not possible from what I have tried because there is no AND/OR flags in the search engine. 
I know that high cardinality labels is an issue but it could be something that one has to add by them selves and not automatically added. 

One way could be that you would have to actively chose if you want to use one high cardinality label and you then know that there are some drawbacks?

In grep you can do multiple greps instead but I dont know if that is somehow possible in the Explore UI?

**Comment by gouthamve** [comment]
We'll be adding support for AND filtering, see: https://github.com/grafana/loki/pull/31

This is modeled after how we (I) do grep on logs: `kubectl logs -l name=ingester --since=12h | grep org_id=<id> | grep -v 429 | grep -v 400` (taken from my bash history :P). It would be interesting to see how to add `OR` filtering. How would the semantics look like? Can you not add it as part of a single grep instance (grep "X|Y")?

**Comment by ventris** [comment]
Adding the AND filtering solves some of the problems that I can see. The OR instance can be solved with pipe I guess.

**Comment by gouthamve** [comment]
> For instance if you add custom labels in Prometheus to know what environment the metrics are coming from it would be great to be able to add this custom label to Loki events as well so they can be collaborated easier.

Yess! We use relabelling_rules/external to configure the agent (promtail) and you should technically be able to add the same extra labels to the logs.

While I get your concern, I am not sure about ability to tag streams at ingest time. While I think we should limit the labels to be indexed to what the agent sends us, we will certainly look at tagging logs at ingest time and what the implications are.

**Comment by sandstrom** [comment]
@gouthamve Thanks for your quick response and for considering this!

I've broken this into two (high cardinality and ingest time labeling), to make the discussion easier. This issue is now only about setting metadata at ingest time (both issues link to each other in their description).

(if you want you can delete your cardinality question above, and re-add it in the other issue)

**Comment by base698** [comment]
@woodsaj Any idea how to get the Wrap function to fire?  I've created another config type to support this and it's not firing.  https://github.com/grafana/loki/blob/master/pkg/promtail/api/entry_parser.go#L57  This Wrap fires when the entryparser in the yaml is parsed.  Added the type here:  	EntryParser            EntryParser                      `yaml:"entry_parser"`

**Comment by base698** [comment]
Created Pull Request to continue the conversation.

**Comment by slim-bean** [comment]
It took a little while to get this all sorted out, but with the 0.1.0 release there is included a [pipeline](https://github.com/grafana/loki/blob/master/docs/logentry/processing-log-lines.md) which includes a [regex stage](https://github.com/grafana/loki/blob/master/docs/logentry/processing-log-lines.md#regex) that allows extraction of log data to be used in labels and/or metrics using regular expressions.

**Comment by sandstrom** [comment]
@slim-bean Awesome! 💯
