### ISSUE TITLE
Save logs to ElasticSearch

### ISSUE THREAD

**Issue by TakumaNakagame** [grafana/loki#912]
I want to use ElasticSearch as the log data storage destination

I am building Kubernetes on premises. Building a PersistentVolume in Loki is hard.
But there is already ElasticSearch. It is best to be able to store logs in ElasticSearch.

Like Prometheus RemoteStorage.

**Comment by sh0rez** [comment]
Hi!

It might be me, but I do not get the additional value of using ElasticSearch, because Loki is considered to be a direct replacement for it in most use-cases.

If you want to use ElasticSearch why not use `fluentd` or `filebeat`, ship directly to ElasticSearch and use Grafana's Explore feature (https://grafana.com/docs/features/datasources/elasticsearch/#logs-beta) to peek at those. This should give you a similar experience Loki provides.

Or are there any benefits of having Loki in the middle I am not aware of?

**Comment by TakumaNakagame** [comment]
Thank you for the response.

I already have ElasticSearch in my environment. (PB grade)
Therefore, the easiest way to persist data was to transfer it here. The Cortex architecture is great, but not easy.
I want to use Loki for log alerts. I understand that Loki replaces ElasticSearch, but alerts are a great feature that only exists in Loki.

The ability to use the alert function and Grafana integration is a big advantage.

**Comment by sh0rez** [comment]
Hi, if you are only up for alerting, you might already be satisfied with the Elasticsearch alerting feature of Grafana itself: https://grafana.com/docs/guides/whats-new-in-v5-2/#elasticsearch-alerting

I imagine it easier to stick to your Elasticsearch setup and integrate alerting, instead of running Loki as well just for that purpose

**Comment by TakumaNakagame** [comment]
Thank you for response.
I tried Grafana Alerting. This was certainly enough.

Thank you!

**Comment by sh0rez** [comment]
Great to hear that you have been able to solve your problem! Feel free to reach out for further questions on Slack!
