### ISSUE TITLE
A way to ingest syslog messages over the network and into Loki

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#935]
**Is your feature request related to a problem? Please describe.**

There are many devices such as firewalls/network appliances/switches etc that don't write log files or run on architectures too difficult to compile promtail for, however many of them support shipping syslogs (as well as pretty much all *nix servers in general).  It would be great to have a way to receive these syslogs and get them into Loki

**Describe the solution you'd like**

I think this needs some discussion, should Promtail be updated to receive these syslogs and then send them to Loki? Or another tool created? Or Loki updated to receive them directly?

**Comment by geekodour** [comment]
I was initially confused by the  fact that loki is described as the prometheus for logs but the scraping targets go in promtail, keeping that in mind I think updating promtail to receive these syslogs and then send them to Loki will be a better idea.

How different will this be from pushgateway for logs? https://github.com/prometheus/pushgateway

**Comment by sh0rez** [comment]
> I was initially confused by the fact that loki is described as the prometheus for logs but the scraping targets go in promtail, keeping that in mind I think updating promtail to receive these syslogs and then send them to Loki will be a better idea.

This is not entirely true. Loki basically follows the Prometheus pattern, although it is not that obvious:
- Your application is logging (it is exposing logs, as it would expose metrics).
- Promtail is "scraping" (tailing) those logs, just like a Prometheus would. The difference here is, that Prometheus's job may go further than scraping, because it includes a database, so it can run standalone, depending on the configuration.
- Loki is a remote backend that Promtail pushes to, just like Prometheus **pushes** scraped (pulled) metrics to the `remote_write` backend (Cortex, etc.).

So in this world, the `loki` component would be `cortex`, while `promtail` is Prometheus minus the database. 



Keeping that in mind, I believe it would be more frictionless to re-use the component that is already being pushed to (the `loki` server) and let it expose a `syslog` endpoint.

**Comment by cyriltovena** [comment]
Fluent-bit plugin seems to support syslog input would that solve the issue ? Or do we really want to have this in promtail ?

**Comment by genebean** [comment]
I vote for solving In promtail 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bastjan** [comment]
Hi!

I created a draft pull request #1275 how syslog integration could look like in loki. I'm willing to work out the current limitations if the pull request is something you'd like to add to promtail.

What it does:
* Ingest IETF syslog (RFC5424) without octet count framing over TCP.
* Parse the message for relabeling.

What it does not:
* Ingest BSD syslog (RFC3164) / ingest over UDP.

**Comment by cdickmann** [comment]
I am a bit confused about the architecture. It seems that syslog is being added promtail, not the ingester. Woouldn't it make most sense to have the ingester accept the syslog protocol?

**Comment by roidelapluie** [comment]
No as you can alter labels etc in promtail. Plus you generally want to syslog to local machine.

**Comment by cdickmann** [comment]
I have always seen syslog as a log aggregation scheme where you run a central log service and then all hosts send over logs via syslog.

**Comment by carwyn** [comment]
> I have always seen syslog as a log aggregation scheme where you run a central log service and then all hosts send over logs via syslog.

A good example of this would be network swtiches, the low level iBMC/LOM management boards on servers or enterprise hardware such as storage area network hardware. These tend to be embedded systems with little hope of running additional software on most. Stats and loging are frequently SNMP and Syslog.

**Comment by roidelapluie** [comment]
Nothing prevents you to have a centralized promtail

**Comment by sh0rez** [comment]
> Nothing prevents you to have a centralized promtail

I don't fully agree with this. Promtail is designed as a more or less lightweight **agent**, meaning that it is deployed onto every machine to ship local logs to the **central loki server**.

IMHO a syslog receiver in promtail does not play well with other design decisions, because at the moment `promtail` is the pushing entity, not the piece of software that is pushed to.  

I would prefer the already being pushed-to app (`loki`) to accept the syslog protocol.  
In case this is difficult because we do not want to different API's on one application, a small `syslog-gateway` service could do what is already drafted as a PR, just not inside of promtail.

**Comment by sh0rez** [comment]
I see the idea of using syslog only locally and it sounds fair to have this feature in promtail, as it is available locally anyways.

However, the `promtail` binary is already pretty big and far from a lightweight agent and adding something that does NOT HAVE to be solved in there but only COULD be – not a big fan of it. Don't think it hurts a lot to deploy a `syslog-gateway` agent at the place it fits best in your architecture either

**Comment by genebean** [comment]
I like the idea of ingesting syslog via promtail.

**Comment by sh0rez** [comment]
> I like the idea of ingesting syslog via promtail.

Hey @genebean could you please explain why you like this and what benefits there are over other approaches?

**Comment by genebean** [comment]
One reason I like it is that as a user of the hosted Loki, promtail is how I get logs to Loki. As mentioned earlier, you can do labels and such with promtail. By allowing promtail to receive logs I can have consistently labeled and formatted logs in Loke regardless of if they originate in k8s, a traditional server, or a network device. That consistent experience and output is very nice from a UX perspective. This is, or at least used to be, a common thing done with logstash. I mention logstash because the promtail/Loki/Grafana combo is touted as an ELK alternative. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slim-bean** [comment]
Sorry I'm late to rejoin the party but I wan to add a few of my opinions here as well.

I definitely want to support ingesting syslogs via promtail.  I am **not** in favor of creating a separate push agent for this, mainly for the reasons Loki itself has seen so much success with the single binary approach.  I do not want to have to point people at a separate project/repo/binary/config etc to be able to ingest syslog on premise into loki (weather that be on the local machine or as a single promtail aggregating syslog messages from all over the network), I really want there to be a consistent experience on the sending side via promtail.  We should handle this by making sure the code is modular and properly packaged within promtail to make sure it can be configured to be used or not used as desired via config.  

I am not necessarily opposed to having Loki ingest the syslogs directly however I'm not immediately concerned with implementing this if we have this support via promtail.  Mainly because I _think_ in most cases people would be running Loki in a separate network or firewall zone as some or all of their syslog generating sources.  I think the https support and the snappy compressed protobuf we get from promtail is a big advantage for shipping syslogs between networks or over the internet.  I would think in most cases people would deploy a promtail(s) in a network and have syslog forward to it, and then it can forward to Loki.  @sh0rez I also think this includes the idea of running promtail as a centralized agent as well.  I think this would work well for many people. 

I also generally don't consider the size of the binary in regards to the "weight" of the application (within reason), I think we are still less than 100MB which is hardly tiny but manageable.  More so I think the CPU and Memory requirements are more important, of which we generally see Promtail consuming 750mCPU in the worst cases and about 300MB of memory (although some of this I would like to blame on Go > 1.12 in regards to how memory is returned to the system)  And this is processing 6000-7000 log lines per second.

If you are in the case where you are running Loki along side all your syslog sources, then yes, you would need to run a promtail instance which isn't gaining you much, but I think until there is enough demand for this use case we probably won't see syslog ingestion directly by loki right away.

**Comment by bastjan** [comment]
> However, the `promtail` binary is already pretty big and far from a lightweight agent and adding something that does NOT HAVE to be solved in there but only COULD be – not a big fan of it. Don't think it hurts a lot to deploy a `syslog-gateway` agent at the place it fits best in your architecture either

I don't think syslog fits into prom**tail** that well mostly because it is push-based. I've added it for convenience. But I don't care either way if it is in promtail or a separate binary.

I use it for both local and non-local syslog.

> I think the https support and the snappy compressed protobuf we get from promtail is a big advantage for shipping syslogs between networks or over the internet.

I see this as a big advantage. Syslog does support TLS but it is hit or miss depending on the vendor in my experience.
(Re)labeling is important too, or you would lose most of the awesome metadata and log stream selection features.

**Comment by cdickmann** [comment]
Great discussion and thanks to @slim-bean for outlining detailed design considerations. I think where I was coming from was an old-school enterprise world. There are many products which have "syslog support" in the form of the entire (multi-node) product being able to take a single syslog destination. And then there being one single central service to aggregate, managed by someone different. 

The proposed design (central loki doesn't directly support syslog) means I can't easily use loki as a drop-in replacement. I need to deploy a more local promtail-service. I think it is not a bad design, and the reasons outlined (e.g. TLS/snappy) are actually compelling. It is just a more complex design as Loki wouldn't be a drop-in replacement as easily. But I agree that can be mitigated by running a promtail alongside the central loki.

**Comment by cyriltovena** [comment]
We could definitely add an optional promtail  gateway deployment in helm to ease this use case.

I think we can start with promtail without too much compromise, there’s a lot of appealing features in it.

Another idea could be to embed promtail in Loki as a module, which can be turned on/off via the yaml/flag config.

**Comment by slim-bean** [comment]
> Another idea could be to embed promtail in Loki as a module, which can be turned on/off via the yaml/flag config.
👍

**Comment by roidelapluie** [comment]
Note: we are using Loki outside of kube so we are not interested in complexity. We would prefer syslog in promtail.

**Comment by carwyn** [comment]
Running a promtail instance or even a distinct dedicated binary as a proxy isn't really a problem in our case, perhaps run one or two per site. Many classes of older equipment only support UDP and/or insecure transmission, often jailed on their own VLAN, meaning bridging to something more secure before forwarding and aggregation has benefits. For devices that don't support multiple syslog destination for redundancy there's scope for a proxy to duplicate too.

Our use case is a multi-site university campus with network, IoT, buildings management as well as more typical datacentre and cloud use cases to try and make sense of.

**Comment by basroovers** [comment]
Any update on syslog over udp? I would really like to get some syslogs from network devices like switches, load balancers and firewalls but they only support udp.

**Comment by bastjan** [comment]
It is recommended to use syslog-ng or rsyslog in front of promtail, both support UDP. See [here](https://github.com/grafana/loki/blob/v1.5.0/docs/clients/promtail/scraping.md#syslog-receiver) for configuration.

The Syslog protocol never really standardised and every vendor has a slightly different implementation. Both rsyslog and syslog-ng account for many special implementations (cisco, ...) out of the box. Using them allows for the highest compatibility possible.
