### ISSUE TITLE
Fluentd / Fluentbit comparison to Loki / Promtail

### ISSUE THREAD

**Issue by geota** [grafana/loki#94]
Fluentd is one primary players in this space. It would be worthwhile for potential users of loki / promtail to understand the differences between these two log aggregators / forwarders.

**Comment by javefang** [comment]
According to Grafana Lab guys, it looks like promtail will label each log message with pod labels while the fluentd plugin doesn't automatically and has to be configured (then it's hard to make it dynamic if pods have different labels I guess). I don't really understand why the fluentd plugin can't do the same thing. Some clarification from the maintainer will be great i think?

**Comment by cyriltovena** [comment]
@rfratto this should be covered by our new documentation.

**Comment by mdgreenwald** [comment]
> @rfratto this should be covered by our new documentation.

Do you have a link to the relevant documentation?

**Comment by rfratto** [comment]
@mdgreenwald 

Sorry for the confusion, he's just saying I should add this information in our docs revamp that I'm working on this week.

**Comment by neoakris** [comment]
@rfratto 
If that's the case can you add answers to these questions in your docs or at least mention if it's possible?

Questions: 
1.) Which is better today for generating Alert Manager Alerts from logs? Promtail or fluentd? Are there plans to make one better at sending Alerts on log messages to AM in the future? 
2.) My understanding is both can create Prometheus metrics from logs and AM alerts can be generated from that. Are there plans to make it easier for Promtail to send alerts to AM directly? Current solutions seem like a workaround or will that be the end goal, (which makes some sense from a consistency stand point.)
3.) I currently believe (from reading/no hands-on) fluentd is better at transforming logs and promtail is better at syncing tags. Can your documentation tell us a way of getting the best of both worlds? 
Example: promtail --> autoconfigured from Prometheus Operator ServiceMonitor objects spawning an auto generated Prometheus Scrape Config --> (gain labels sync with prometheus) --> ship to fluentbit/fluentd --> (gain their mature ecosystem of mature / off the shelf ready to use log parser plugins etc.) --> use fluentd plugin to ship to Loki. 

Side Benefit of the above strategy:
- Maybe fluentd will be best/easier to config for generating AM alerts, maybe promtail will be best, by hitting both you can use either. 
- If the Loki staff adopt it, it could simplify the scope of work around promtail. 
---
My understanding is that:
1.) Kubernetes Ingress objects allow you to chunk a 200,000 nginx config into 500 snippets of LB config called Ingress objects.
2.) Prometheus Operator's ServiceMonitor objects work similar to Ingress objects, You can create a bunch of ServiceMonitor objects to auto-generate Prometheus Scrape config. 
3.) Loki uses the same config as Prometheus, so you should be able to autoconfigure Promtail by pointing it to auto-generated Prometheus Scrape config in theory.
4.) The reason Promtail exists is for consistency of tags between Prometheus Metrics and Loki Log. 
5.) fluentd has tons of plugins / pipelines / off the shelf transformations
---

**Comment by rfratto** [comment]
@neoakris My current PR is [here](https://github.com/grafana/loki/pull/982) with the current comparison document [here](https://github.com/grafana/loki/blob/260444726ac71b25d24b7c95c9fc6bb1ad4373ad/docs/overview/comparisons.md).

I'm hesitant to add work-in-progress details to our documentation since there's not much point comparing a fully featured product to a hypothetical, but I'll try to address your questions to the best of my ability here. 

I'm not sure that I would say we want Promtail to be better than fluentd since the use cases are different. As you've mentioned, Promtail is a tailored solution for Loki; since it shares code with Prometheus, you can end up switching between metrics and logs on the fly. But that doesn't necessarily mean that the Prometheus config and Loki config are _exactly_ the same either:

1. Promtail can only scrape logs from the machine Promtail is running on since it needs to read files from disk. There's some little extra work required in the scrape configurations to get this working properly. #1012 was opened to try to help with this, though 
2. Promtail may be configured with extra labels that don't make sense for metrics, like filename. 

As far as alerting goes, we've fairly recently made Loki's API Prometheus-compatible. I believe this means you can now generate alerts from Loki queries, and I think @slim-bean has done some work playing around with this. There aren't any current plans to have Promtail interact directly with Alert Manager, but that's not a hard stance. 

For getting Promtail to place nice with Fluentd, that's not a use case we're covering (yet?). Promtail can only ingest data from text files on disk/systemd and can only send it out to Loki. I can pretty confidently say that we can't use Fluentd to simplify the work around Promtail since we don't want to add any more required dependencies than we already have (in fact; we're working to minimize dependencies now). 

We do want to give extra power to Promtail with its pipelines, and I think supporting external libraries would help with that. I've just opened #1055 to track this.

Despite all I said here, I'm definitely not an authoritative voice on Loki :slightly_smiling_face: I'd recommend for you to open up issues for any ideas you might have.

**Comment by adamdecaf** [comment]
FYI, there's a logging-operator project that just released a v2 which would be good to compare loki against. They seem to use fluentbit (format) as well, so it's in the same space as loki.

https://github.com/banzaicloud/logging-operator
