### ISSUE TITLE
Dashboards mixin

### ISSUE THREAD

**Issue by DanielCastronovo** [grafana/loki#9469]
**Describe the bug**
Grafana dashboards are partially empty

**To Reproduce**
1. Install Mixin dashboards (by Helm or with jb install)
2. Launch dashboards on Grafana

**Expected behavior**
See all metrics

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm
 - ServiceMonitor enabled

**Screenshots, Promtail config, or terminal output**
Many metrics does not exist or are empty.

**Comment by sjentzsch** [comment]
We are facing the same issues, and as e.g. outlined by https://github.com/grafana/loki/issues/4838, there needs to be quite some modifications required to make it work for helm deployments.

These are especially related to the `job` label. In our case, we fixed it with jsonnet using overlays/overwrites, for example (keep in mind, in our case the helm chart release is called `loki-distributed`; might be different in your case):

```
grafanaDashboards+: {
    'loki-operational.json'+:{
      jobMatchers:: {
        cortexgateway: [utils.selector.re('job', 'loki-distributed-cortex-gw(-internal)?')],
        distributor: [utils.selector.re('job', 'loki-distributed-%s' % (if $._config.ssd.enabled then '%s-write' % $._config.ssd.pod_prefix_matcher else 'distributor'))],
        ingester: [utils.selector.re('job', 'loki-distributed-%s' % (if $._config.ssd.enabled then '%s-write' % $._config.ssd.pod_prefix_matcher else 'ingester.*'))],
        querier: [utils.selector.re('job', 'loki-distributed-%s' % (if $._config.ssd.enabled then '%s-read' % $._config.ssd.pod_prefix_matcher else 'querier'))],
        queryFrontend: [utils.selector.re('job', 'loki-distributed-%s' % (if $._config.ssd.enabled then '%s-read' % $._config.ssd.pod_prefix_matcher else 'query-frontend'))],
      },
      panels:
        std.map(
          function(item)
            if item.id == 94 then
              item+ {
                panels:
                  std.map(
                    function(panelItem)
                      if panelItem.id == 96 then
                        panelItem+ {
                          targets:
                            std.map(
                              function(targetItem)
                                targetItem+ {
                                  expr: 'sum by(reason) (rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"loki-distributed-ingester\", namespace=~\"$namespace\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"loki-distributed-ingester\", namespace=~\"$namespace\"}[$__rate_interval]))'
                                },
                              super.targets
                            )
                        }
                      else
                        panelItem,
                    super.panels
                  )
              }
            else
              item,
          super.panels
        ),
      timezone: 'browser',
    },
  },
```

This of course is just a workaround; I would also love for the mixin to be more configurable in this regard. At least with this pattern we could still vendor it, otherwise I guess we would choose to make changes on top of the rendered manifests...

Also, in our case, we are scraping data every 30s, but the default scrape interval of the datasource is set to 15s, resulting in aggregations using `$__rate_interval` not showing data for certain time frames as 15s is used for minimal step interval. Changing to 30s on our datasource scrape interval setting within Grafana fixed that issue for us.

**Comment by samarara** [comment]
I was able to get it working by turning ssd on in `config.libsonnet`

**Comment by sjentzsch** [comment]
@DanielCastronovo if you build yourself via jsonnet, see https://github.com/grafana/loki/blob/main/production/loki-mixin/config.libsonnet#L26C13-L26C13 - otherwise there are also pre-compiled ones (https://github.com/grafana/loki/tree/main/production/loki-mixin-compiled-ssd)
