### ISSUE TITLE
fluentbit plugin latest docker image not working

### ISSUE THREAD

**Issue by lucacorti** [grafana/loki#9932]
**Describe the bug**

The latest docker image from docker hub (`grafana/fluent-bit-plugin-loki:main`) fails to start.
Reverting to `grafana/fluent-bit-plugin-loki:main-9e19ff0-amd64` seems to work fine.

**To Reproduce**

Just start the image with `docker run`

**Expected behavior**

The image starting normally.

**Environment:**
 - Infrastructure: AWS ECS, docker
 - Deployment tool: terraform

**Screenshots, Promtail config, or terminal output**
```
[error] [plugin] error loading proxy plugin: /fluent-bit/bin/out_grafana_loki.so
[proxy] error opening plugin /fluent-bit/bin/out_grafana_loki.so: '/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /fluent-bit/bin/out_grafana_loki.so)'
```

**Comment by aswath-betaflux** [comment]
Same Issue I also face. 

[proxy] error opening plugin /fluent-bit/bin/out_grafana_loki.so: '/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /fluent-bit/bin/out_grafana_loki.so)

**Comment by JoaoPedroFerreira** [comment]
I have the same error

**Comment by lucacorti** [comment]
This still does not seem to work on linux/arm64:

```
$ docker run --platform linux/arm64 --env-file env -it grafana/fluent-bit-plugin-loki
Unable to find image 'grafana/fluent-bit-plugin-loki:latest' locally
latest: Pulling from grafana/fluent-bit-plugin-loki
Digest: sha256:b29f08d9210a11dd5d9e0e6a29a82fd548adb581d3a6a17e4449098fec25c530
Status: Image is up to date for grafana/fluent-bit-plugin-loki:latest
docker: image with reference docker.io/grafana/fluent-bit-plugin-loki:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```

**Comment by sossaman** [comment]
Hello,
I have just tried to run a container based on the image grafana/fluent-bit-plugin-loki:2.8.6-amd64.
It still shows the same error:
` error opening plugin /fluent-bit/bin/out_grafana_loki.so: '/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /fluent-bit/bin/out_grafana_loki.so)'`
Is it so difficult to fix it ?

**Comment by vasuarv** [comment]
I was able to make some progress on this issue. The issue is due to the fact the base image that is being used is based of debian 11 which has glibc 2.31, and the golang build base image has glibc 2.36 in it. So the library generated is incompatible, which is what the error is showing.
There are 2 ways to solve the issue:
1. Update the fluent-bit base image to debian 12 which has glibc version 2.36 as well.
2. Update the golang build tool image to use the debian-11 base image.
In my short experiments so far, option 2 does not work out of the box and there is a crash in the shared lib. So the only workable option that I found was option 1. This does mean that the changes are in a the fluent-bit base image itself and not in loki. 
Also as a general observation, this has been broken for a while now, for atleast a couple of releases, which indicates that there is no real testing that is going on for this at all.
