### ISSUE TITLE
ingester WAL replay takes too long

### ISSUE THREAD

**Issue by stringang** [grafana/loki#9939]
**Describe the bug**
I am running `loki-distributed` in k8s. when I restart the `ingester` instance, I find that the `ingester4` instance takes a long time to complete the `WAL replay`, the other instances take much less time to complete.

```
level=info ts=2023-07-13T18:49:54.185275394Z caller=ingester.go:432 msg="recovered WAL checkpoint recovery finished" elapsed=1h25m27.618187613s errors=false
```

I looked at the ingester metrics and found that the `loki_ingester_streams_created_total` metric for `ingester4` is more than triple the value of the other instances.

**To Reproduce**
1. Started Loki (SHA or version): 2.8.2

**Expected behavior**

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
metric:
<img width="1850" alt="image" src="https://github.com/grafana/loki/assets/14845458/5f4c2261-7aa3-43eb-b152-42ba7bb2b06f">

<img width="1845" alt="image" src="https://github.com/grafana/loki/assets/14845458/e5987544-87aa-4132-b39e-07ca2c4a192c">

**Comment by salvacorts** [comment]
> **To Reproduce**
>Steps to reproduce the behavior:
>
>Started Loki (SHA or version): 2.8.2
>
> **Expected behavior**
>A clear and concise description of what you expected to happen.

Can you elaborate on the _how to reproduce_? Also, looks like you missed filling the _Expected behaviour_ section. Thank you!

> I looked at the ingester metrics and found that the loki_ingester_streams_created_total metric for ingester4 is more than triple the value of the other instances.

> I find that the ingester4 instance takes a long time to complete the WAL replay, the other instances take much less time to complete.

That might be somehow expected. [The WAL][1] stores all the logs received by an ingester that hasn't been flushed yet. When an ingester restarts, it will start replaying the WAL. My assumption is that the WAL for `ingester-4` is considerably bigger than for the rest, and therefore it takes longer to replay. You can verify this by inspecting the directory where the WAL Is written to, looking at the size of the WAL files in there.

Also, I feel like this issue is more a _Question_ than a _Bug_ report. If you agree, I think it'd be better to open a thread in any of the support channels we run for the community (e.g. [Grafana's Public Slack](https://slack.grafana.com/), [community forum](https://community.grafana.com/c/grafana-loki/41).)

[1]: https://grafana.com/docs/loki/latest/operations/storage/wal/#write-ahead-log

**Comment by stringang** [comment]
when restarting the `ingester` into `WAL replay` takes too long and causes `liveness` to fail, it will go into a `restart<--> WAL replay` dead loop

**Comment by stringang** [comment]
`ingester` waits for the `recovering from checkpoint`  and `recovering from WAL` to finish before starting.
